// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Ops
{
    [Table("Ops.CreditorUploadHistory")]
    public class CreditorUploadHistory
    {
        [Key]
        public int Id { get; set; }
        public string CreditorUploadHistoryId { get; set; }
        public string CreditorId { get; set; }
        public DateTime ProcessStartTime { get; set; }
        public string? DataImportId { get; set; }
        public string FileNames { get; set; }
        public int InvoiceCount { get; set; }
        public int ContactsCount { get; set; }
        public int PaymentsCount { get; set; }
        public int MetaDataCount { get; set; }
        public int NetNewInvoicesCount { get; set; }
        public int VoidedInvoicesCount { get; set; }
        public int InvoicesUpdatedCount { get; set; }
        public decimal TotalInvoiceUpload { get; set; }
        public decimal AverageDaysPastDue { get; set; }
        public string? ErrorsOrWarnings { get; set; }
        public int TotalNewMattersUploaded { get; set; }
    }
}
