// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Ops
{
    [Table("Ops.HttpMessageExchange")]
    public class HttpMessageExchange
    {
        [Key]
        public Guid Id { get; set; }
        public string ApiName { get; set; }
        public string? ApiVersion { get; set; }
        public string? RequestContent { get; set; }
        public string? RequestHeaders { get; set; }
        public string RequestMethod { get; set; }
        public string RequestUri { get; set; }
        public DateTime RequestTimestamp { get; set; }
        public string? ResponseContent { get; set; }
        public string? ResponseHeaders { get; set; }
        public DateTime ResponseTimestamp { get; set; }
        public string? ReasonPhrase { get; set; }
        public string? StatusCode { get; set; }
        public bool IsSuccessExchange { get; set; }
    }
}
