// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Ops
{
    [Table("Ops.Set")]
    public class Set
    {
        public string Key { get; set; }
        public double Score { get; set; }
        public string Value { get; set; }
        public DateTime? ExpireAt { get; set; }
        // NOTE: Composite primary key detected; use EF Core Fluent API to configure:
        // modelBuilder.Entity<Set>().HasKey(e => new { /* add key parts here */ });
    }
}
