// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.Comms
{
    public enum EmailMessageRecipientType
    {
        To = 1,
        CC = 1,
        BCC = 1,
    }
}
