// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Enums.Comms
{
    public enum EmailMessageRecipientType
    {
        To = 1,
        CC = 1,
        BCC = 1,
    }
}
