// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Metrics
{
    [Table("Metrics.AccountInvoiceActivityMetaData")]
    public class AccountInvoiceActivityMetaData
    {
        [Key]
        public int AccountInvoiceActivityId { get; set; }
        public string? MetaData { get; set; }
    }
}
