// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.AccountInvoiceClicks")]
    public class AccountInvoiceClicks
    {
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string RefferenceCode { get; set; }
        public DateTime TimeStamp { get; set; }
    }
}
