// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.AccountInvoiceActivity")]
    public class AccountInvoiceActivity
    {
        [Key]
        public int Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public string CreditorId { get; set; }
        public DateTime ActivityDate { get; set; }
        public int ActivityType { get; set; }
        public int? CommunicationTemplate { get; set; }
        public int? NotificationType { get; set; }
        public string? MetaData { get; set; }
        public string? UniqueActivityId { get; set; }
    }
}
