// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.AccountInvoiceActivityMetaData")]
    public class AccountInvoiceActivityMetaData
    {
        [Key]
        public int AccountInvoiceActivityId { get; set; }
        public string? MetaData { get; set; }
    }
}
