// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.AnalyticsDashboard")]
    public class AnalyticsDashboard
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public DateTime? TotalFrom { get; set; }
        public DateTime? TotalTo { get; set; }
        public DateTime TotalDate { get; set; }
        public DateTime? CalculatedAt { get; set; }
        public string MetricName { get; set; }
        public decimal? TotalAllTime { get; set; }
        public decimal? Total { get; set; }
    }
}
