// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.AnalyticEvent")]
    public class AnalyticEvent
    {
        public int Id { get; set; }
        public string AnalyticEventId { get; set; }
        public string CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string? Payload { get; set; }
        public string CorrelationId { get; set; }
        public string Paymentkey { get; set; }
        public DateTime OccurredAt { get; set; }
        public int EventType { get; set; }
    }
}
