// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Metrics
{
    [Table("Metrics.AutomationCampaignCommFailures")]
    public class AutomationCampaignCommFailures
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string InvoiceId { get; set; }
        public short? InvoiceStatus { get; set; }
        public decimal? AmountDue { get; set; }
        public decimal? AmountPaid { get; set; }
        public string? CampaignTags { get; set; }
        public string Reason { get; set; }
        public DateTime OccuredAt { get; set; }
    }
}
