// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.CampaignMetricMessageStatus")]
    public class CampaignMetricMessageStatus
    {
        [Key]
        public int Id { get; set; }
        public int CampaignMetricId { get; set; }
        public int MessageType { get; set; }
        public string? MessageTypeName { get; set; }
        public int MessageStatus { get; set; }
        public string? MessageStatusName { get; set; }
        public int? TotalMessages { get; set; }
        public DateTime? FirstMessage { get; set; }
        public DateTime? LastMessage { get; set; }
    }
}
