// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.CampaignMetric")]
    public class CampaignMetric
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string CompanyName { get; set; }
        public string? CampaignId { get; set; }
        public string? CampaignName { get; set; }
        public DateTime? FirstCampaignMessageDate { get; set; }
        public DateTime? LastCampaignMessageDate { get; set; }
        public string? AutoStartCampaignId { get; set; }
    }
}
