// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.CampaignMetricOverview")]
    public class CampaignMetricOverview
    {
        [Key]
        public int Id { get; set; }
        public int CampaignMetricId { get; set; }
        public string OverviewType { get; set; }
        public int? TotalMessages { get; set; }
        public DateTime? LastUpdate { get; set; }
    }
}
