// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Metrics
{
    [Table("Metrics.NotificationMetric")]
    public class NotificationMetric
    {
        [Key]
        public int Id { get; set; }
        public string NotificationMetricId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string CreditorId { get; set; }
        public string? PolicyId { get; set; }
        public string? TemplatedText { get; set; }
        public int NotificationType { get; set; }
        public int NotificationStatus { get; set; }
        public DateTime OccurredAt { get; set; }
        public string? ErrorMessage { get; set; }
        public string? IpAddress { get; set; }
        public string? UserAgent { get; set; }
        public string? Url { get; set; }
        public string UniqueMessageId { get; set; }
        public int CommunicationTemplate { get; set; }
        public string? SentToAddress { get; set; }
        public int? NotificationSource { get; set; }
        public string? CampaignId { get; set; }
        public string? ScheduleId { get; set; }
        [Computed]
        public decimal? Segments { get; set; }
        public string? InvoiceCampaignScheduleId { get; set; }
        public string? InvoiceCampaignTrackingId { get; set; }
        public string? TemplateId { get; set; }
        public string? AccountContactId { get; set; }
        public string? ErrorCode { get; set; }
        public int? FailureReason { get; set; }
        public string? FailureDetail { get; set; }
        public string? SentBccAddress { get; set; }
        public string? AutoStartCampaignId { get; set; }
    }
}
