// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Metrics
{
    [Table("Metrics.NotificationCampaignMetric")]
    public class NotificationCampaignMetric
    {
        [Key]
        public int Id { get; set; }
        public string NotificationCampaignMetricId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string? CampaignId { get; set; }
        public string? ScheduleId { get; set; }
        public string? AccountTransactionCorrelationId { get; set; }
        public string? AccountPaymentId { get; set; }
        public string UniqueMessageId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public string? RecurringPaymentId { get; set; }
        public string? InvoiceCampaignTrackingId { get; set; }
        public string? InvoiceCampaignScheduleId { get; set; }
    }
}
