// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.NotificationMetricBcc")]
    public class NotificationMetricBcc
    {
        public int NotificationMetricBccId { get; set; }
        [Key]
        public string UniqueMessageId { get; set; }
        public DateTime? DeliveredOn { get; set; }
        public DateTime? SentOn { get; set; }
        public DateTime? FailedOn { get; set; }
        public DateTime? BlockedOn { get; set; }
        public string EmailAddress { get; set; }
    }
}
