// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.NotificationMetaData")]
    public class NotificationMetaData
    {
        [Key]
        public int Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public string NotificationMetricId { get; set; }
        public string UniqueMessageId { get; set; }
        public string MetaDataName { get; set; }
        public string? MetaDataValue { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }
}
