// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Metrics
{
    [Table("Metrics.TwilioMetric")]
    public class TwilioMetric
    {
        [Key]
        public int Id { get; set; }
        public string TwilioMetricId { get; set; }
        public string? CampaignId { get; set; }
        public string? AutoStartCampaignUniqueId { get; set; }
        public string? ScheduleId { get; set; }
        public string CreditorId { get; set; }
        public string? AccountInvoiceId { get; set; }
        public string? AccountContactId { get; set; }
        public string SmsMessageSid { get; set; }
        public string To { get; set; }
        public int MessageStatus { get; set; }
        public string MessagingServiceSid { get; set; }
        public int SmsStatus { get; set; }
        public string? From { get; set; }
        public string AccountSid { get; set; }
        public string ApiVersion { get; set; }
        public string MessageSid { get; set; }
        public DateTime ReceivedOn { get; set; }
        public string? TemplatedText { get; set; }
        public string UniqueMessageId { get; set; }
        public int CommunicationTemplate { get; set; }
        public int? ErrorCode { get; set; }
        public string? ErrorMessage { get; set; }
    }
}
