// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.AcimaOauthCache")]
    public class AcimaOauthCache
    {
        [Key]
        public int AcimaOauthCacheId { get; set; }
        public int CreditorId { get; set; }
        public string Token { get; set; }
        public DateTime ExpiresOnUtc { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
    }
}
