// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.BandwidthConfiguration")]
    public class BandwidthConfiguration
    {
        [Key]
        public int BandwidthConfigurationId { get; set; }
        public int? CreditorId { get; set; }
        public string? ApiUrl { get; set; }
        public string? Username { get; set; }
        public string? Password { get; set; }
        public string? ApplicationId { get; set; }
        public string? AccountId { get; set; }
        public string? MobileNumbers { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string? DeletedBy { get; set; }
        public DateTime? DeletedOn { get; set; }
    }
}
