// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.BandwidthIntegrationMobileNumber")]
    public class BandwidthIntegrationMobileNumber
    {
        [Key]
        public int BandwidthIntegrationMobileNumberId { get; set; }
        public int BandwidthIntegrationId { get; set; }
        public string MobileNumber { get; set; }
        public bool IsDisabled { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
