// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.BandwidthIntegration")]
    public class BandwidthIntegration
    {
        [Key]
        public int BandwidthIntegrationId { get; set; }
        public int CreditorId { get; set; }
        public string BaseUrl { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ApplicationId { get; set; }
        public string AccountId { get; set; }
        public int ExpirationInMinutes { get; set; }
        public bool IsDisabled { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
