// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.BraviantIntegration")]
    public class BraviantIntegration
    {
        public int BraviantIntegrationId { get; set; }
        [Key]
        public int CreditorId { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string Origin { get; set; }
        public string OBOToken { get; set; }
        public string IsSandbox { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public string? ApiUrl { get; set; }
    }
}
