// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.ChannelPaymentIntegration")]
    public class ChannelPaymentIntegration
    {
        public int ChannelPaymentIntegrationId { get; set; }
        [Key]
        public int CreditorId { get; set; }
        public string ApiUrl { get; set; }
        public string PrivateKey { get; set; }
        public string SharedKey { get; set; }
        public string? Currency { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
        public bool? ExcludeCardFee { get; set; }
        public string? MerchantId { get; set; }
    }
}
