// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.CreditorConfiguration")]
    public class CreditorConfiguration
    {
        public int CreditorConfigurationId { get; set; }
        public int ConfigurationScopeId { get; set; }
        public int? CreditorId { get; set; }
        public bool? IsPaymentHandlerEnabled { get; set; }
        public bool? IsETLv2Enabled { get; set; }
        public bool? IsStrategyTagInSql { get; set; }
        public int? TagHistoryRetentionDays { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
        public bool IsNewCampaignsApi { get; set; }
        public bool? IsEnablePlanExpiryCheck { get; set; }
        public bool? IsEnableAttachments { get; set; }
        public bool? IsEnableSchedulePayment { get; set; }
        public bool? IsEnableUpdateContactInfo { get; set; }
        public string? SmsSendPaymentReminderEnabled { get; set; }
        public string? EmailSendPaymentReminderEnabled { get; set; }
        public bool? IsPaymentPlanUpdateEnabled { get; set; }
        public bool? IsPaymentPlanCancelEnabled { get; set; }
        public bool? IsETLOnEngineDependencyRemoved { get; set; }
    }
}
