// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.DropCowBoyIntegration")]
    public class DropCowBoyIntegration
    {
        public int DropCowBoyIntegrationId { get; set; }
        public string BaseUrl { get; set; }
        public string BrandId { get; set; }
        public string TeamId { get; set; }
        public string SecretId { get; set; }
        public string VoiceMaleId { get; set; }
        public string VoiceFemaleId { get; set; }
        public bool IsDisabled { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
        public string? CreditorId { get; set; }
        public string? CallerId { get; set; }
        public string? PoolId { get; set; }
    }
}
