// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.EpicPayPayGatewayIntegration")]
    public class EpicPayPayGatewayIntegration
    {
        public int EpicPayIntegrationConfigId { get; set; }
        [Key]
        public int CreditorId { get; set; }
        public string Url { get; set; }
        public string APIKeyId { get; set; }
        public string Password { get; set; }
        public string CurrencyCode { get; set; }
        public string SecCode { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
