// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.FluidPayGatewayIntegration")]
    public class FluidPayGatewayIntegration
    {
        public int FluidPayIntegrationConfigId { get; set; }
        public int CreditorId { get; set; }
        public string ApiUrl { get; set; }
        public string ApiKey { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
