// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.NuveiConfiguration")]
    public class NuveiConfiguration
    {
        [Key]
        public int NuveiConfigurationId { get; set; }
        public int? CreditorId { get; set; }
        public string? ApiUrl { get; set; }
        public string? MerchantId { get; set; }
        public string? MechantSiteId { get; set; }
        public string? ClientId { get; set; }
        public string? ClientSecret { get; set; }
        public string? DefaultCurrency { get; set; }
        public string? DefaultCountry { get; set; }
        public string? DefaultLocale { get; set; }
        public string? WebhookUrl { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string? DeletedBy { get; set; }
        public DateTime? DeletedOn { get; set; }
    }
}
