// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.NuveiPayGatewayIntegration")]
    public class NuveiPayGatewayIntegration
    {
        public int NuveiIntegrationConfigId { get; set; }
        [Key]
        public int CreditorId { get; set; }
        public string ApiUrl { get; set; }
        public string WebhookUrl { get; set; }
        public string MerchantId { get; set; }
        public string MerchantSiteId { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string DefaultCurrency { get; set; }
        public string DefaultCountry { get; set; }
        public string DefaultLocale { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
