// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.PayrocIntegrationAttribute")]
    public class PayrocIntegrationAttribute
    {
        [Key]
        public int PayrocIntegrationAttributeId { get; set; }
        public int PayrocCustomIntegrationId { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public string FieldType { get; set; }
        public string? Format { get; set; }
        public string? UsageType { get; set; }
    }
}
