// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.PayrocIntegration")]
    public class PayrocIntegration
    {
        public int PayrocIntegrationId { get; set; }
        [Key]
        public int CreditorId { get; set; }
        public string ApiUrl { get; set; }
        public string ApiKey { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
        public string? Currency { get; set; }
        public string? TerminalId { get; set; }
        public string? AuthUrl { get; set; }
        public string? OperatorId { get; set; }
        public int? PayrocCustomIntegrationId { get; set; }
    }
}
