// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.RepayPayGatewayIntegration")]
    public class RepayPayGatewayIntegration
    {
        public int RepayIntegrationConfigId { get; set; }
        [Key]
        public int CreditorId { get; set; }
        public string AppDomain { get; set; }
        public string AppToken { get; set; }
        public string MerchantId { get; set; }
        public string Company { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public int? RepayCustomIntegrationId { get; set; }
    }
}
