// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.RepayIntegrationAttribute")]
    public class RepayIntegrationAttribute
    {
        [Key]
        public int RepayIntegrationAttributeId { get; set; }
        public int RepayIntegrationId { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public string FieldType { get; set; }
        public string? Format { get; set; }
        public string? UsageType { get; set; }
        public int? RepayCustomIntegrationId { get; set; }
    }
}
