// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.SendGridIntegration")]
    public class SendGridIntegration
    {
        [Key]
        public int SendGridIntegrationId { get; set; }
        public int CreditorId { get; set; }
        public string ApiKey { get; set; }
        public string SenderAddress { get; set; }
        public string SenderFullName { get; set; }
        public string SenderUsername { get; set; }
        public string SenderPassword { get; set; }
        public int? SmtpPort { get; set; }
        public bool? EnableSsl { get; set; }
        public string? BccAddress { get; set; }
        public string? ReplyToAddress { get; set; }
        public bool IsDisabled { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
