// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.SolutionByTextShortCodeConfiguration")]
    public class SolutionByTextShortCodeConfiguration
    {
        [Key]
        public int Id { get; set; }
        public int? CreditorId { get; set; }
        public string? ApiUrl { get; set; }
        public string? AuthUrl { get; set; }
        public string? GroupId { get; set; }
        public string? ClientId { get; set; }
        public string? ClientSecret { get; set; }
        public string? MobileNumbers { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string? DeletedBy { get; set; }
        public DateTime? DeletedOn { get; set; }
    }
}
