// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.TelgorithmIntegrationMobileNumber")]
    public class TelgorithmIntegrationMobileNumber
    {
        [Key]
        public int TelgorithmIntegrationMobileNumberId { get; set; }
        public int TelgorithmIntegrationId { get; set; }
        public string MobileNumber { get; set; }
        public bool IsDisabled { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
