// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Configuration
{
    [Table("Configuration.TimezoneConfigs")]
    public class TimezoneConfigs
    {
        [Key]
        public int TimezoneConfigId { get; set; }
        public int AreaCode { get; set; }
        public string TimeZone { get; set; }
        public string State { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
