// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Configuration
{
    [Table("Configuration.ZipCodeTimezoneConfigs")]
    public class ZipCodeTimezoneConfigs
    {
        [Key]
        public int ZipCodeTimezoneConfigId { get; set; }
        public string Zip { get; set; }
        public string? City { get; set; }
        public string StateId { get; set; }
        public string? StateName { get; set; }
        public string Country { get; set; }
        public string TimeZone { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
