// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Archive
{
    [Table("Archive.AppNavigationNode")]
    public class AppNavigationNode
    {
        [Key]
        public int RevisionId { get; set; }
        public int NavigationNodeId { get; set; }
        public int? ParentNavigationNodeId { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }
        public string DisplayText { get; set; }
        public string RoutePath { get; set; }
        public string? MatIconName { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string? DeletedBy { get; set; }
        public DateTime? DeletedOn { get; set; }
        public string? PrimeNgIconName { get; set; }
    }
}
