// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Archive
{
    [Table("Archive.BillingClientBillingTermDetail")]
    public class BillingClientBillingTermDetail
    {
        [Key]
        public int RevisionId { get; set; }
        public int ClientBillingTermDetailId { get; set; }
        public int ClientId { get; set; }
        public int CreditorId { get; set; }
        public int TermTypeId { get; set; }
        public decimal FeePercentage { get; set; }
        public int? Min { get; set; }
        public int? Max { get; set; }
        public string Sku { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
