// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Archive
{
    [Table("Archive.ConfigurationAppSetting")]
    public class ConfigurationAppSetting
    {
        [Key]
        public int RevisionId { get; set; }
        public int AppSettingId { get; set; }
        public int? AppServiceId { get; set; }
        public string KeyName { get; set; }
        public string KeyValue { get; set; }
        public int? ExpiresInMinutes { get; set; }
        public string? Description { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
