// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Archive
{
    [Table("Archive.EtlDataFieldMapping")]
    public class EtlDataFieldMapping
    {
        [Key]
        public int RevisionId { get; set; }
        public int DataFieldMappingId { get; set; }
        public int DataFileMappingId { get; set; }
        public int? StringFormatTypeId { get; set; }
        public string TargetFieldName { get; set; }
        public string? Regex { get; set; }
        public string? DateTimeFormat { get; set; }
        public string? StringFormat { get; set; }
        public string? TimeZone { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
