// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Archive
{
    [Table("Archive.EtlDataFileMapping")]
    public class EtlDataFileMapping
    {
        [Key]
        public int RevisionId { get; set; }
        public int DataFileMappingId { get; set; }
        public int CreditorId { get; set; }
        public int FileMappingTypeId { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
