// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Archive
{
    [Table("Archive.EtlFieldMappingValue")]
    public class EtlFieldMappingValue
    {
        [Key]
        public int RevisionId { get; set; }
        public int FieldMappingValueId { get; set; }
        public int DataSourceFieldId { get; set; }
        public string SourceValue { get; set; }
        public string TargetValue { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
