// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Restorable
{
    [Table("Restorable.RestorableTransferReason")]
    public class RestorableTransferReason
    {
        [Key]
        public int RestorableTransferReasonId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}
