// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Views.Campaigns
{
    public class LegacyIdCampaignScheduleView
    {
        public int CampaignId { get; set; }
        public string CampaignLegacyId { get; set; }
        public string? TemplateIds { get; set; }
        public int ScheduleId { get; set; }
        public string ScheduleLegacyId { get; set; }
    }
}
