// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Views.Campaigns
{
    public class LegacyIdCampaignScheduleView
    {
        public int CampaignId { get; set; }
        public string CampaignLegacyId { get; set; }
        public string? TemplateIds { get; set; }
        public int ScheduleId { get; set; }
        public string ScheduleLegacyId { get; set; }
    }
}
