// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Views.Payments
{
    public class RecurringPaymentTransactionView
    {
        public string RecurringPaymentId { get; set; }
        public string AccountPaymentId { get; set; }
        public decimal Amount { get; set; }
        public int TransactionStatus { get; set; }
        public int TransactionType { get; set; }
        public string? TransactionId { get; set; }
        public DateTime TransactionDate { get; set; }
    }
}
