// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.HangFire
{
    [Table("HangFire.Job")]
    public class Job
    {
        [Key]
        public long Id { get; set; }
        public long? StateId { get; set; }
        public string? StateName { get; set; }
        public string InvocationData { get; set; }
        public string Arguments { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? ExpireAt { get; set; }
    }
}
