// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.HangFire
{
    [Table("HangFire.Schema")]
    public class Schema
    {
        [Key]
        public int Version { get; set; }
    }
}
