// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum AccountStatus
    {
        [Description("Awaiting Payment")]
        AwaitingPayment = 0,
        [Description("On Payment Plan")]
        OnPaymentPlan = 1,
        Paid = 2,
        Voided = 3,
        Defaulted = 4,
        Closed = 5,
        [Description("Pending Payment")]
        PendingPayment = 6,
        [Description("Similar to status 1 OnPaymentPlan but for settlement plans")]
        OnSettlementPlan = 7,
        [Description("Similar to status 2 Paid but for settlement plans")]
        Settled = 8,
        [Description("Similar to status 6 PendingPayment but for settlement plans")]
        PendingSIF = 9,
    }
}
