// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum ActivityType
    {
        [Description("Payment Plan Started")]
        PaymentPlanStarted = 0,
        [Description("Payment Plan Cancelled")]
        PaymentPlanCancelled = 1,
        [Description("Payment Plan PaymentDue")]
        PaymentPlanPaymentDue = 2,
        [Description("Payment Plan PaymentRetry")]
        PaymentPlanPaymentRetry = 3,
        [Description("Payment Plan PaymentFailed")]
        PaymentPlanPaymentFailed = 4,
        [Description("Payment Plan Payment Success")]
        PaymentPlanPaymentSuccess = 5,
        [Description("Payment Plan Complete")]
        PaymentPlanComplete = 6,
        [Description("Request CallBack Viewed")]
        RequestCallBackViewed = 7,
        [Description("Payment Plan Viewed")]
        PaymentPlanViewed = 8,
        [Description("Pay Now Viewed")]
        PayNowViewed = 9,
        [Description("Request CallBack Sent")]
        RequestCallBackSent = 10,
        [Description("Adhoc Payment Made")]
        AdhocPaymentMade = 11,
        [Description("Payment Failed")]
        PaymentFailed = 12,
        [Description("Payment Success")]
        PaymentSuccess = 13,
        [Description("Payment Receipt Sent")]
        PaymentReceiptSent = 14,
        [Description("Message Queued")]
        MessageQueued = 15,
        [Description("Message Delivered")]
        MessageDelivered = 16,
        [Description("Message Failed")]
        MessageFailed = 17,
        [Description("Message Opened")]
        MessageOpened = 18,
        [Description("Message Clicked")]
        MessageClicked = 19,
        [Description("Message Spam Report")]
        MessageSpamReport = 20,
        [Description("Message Scheduled")]
        MessageScheduled = 21,
        [Description("Invoice Created")]
        InvoiceCreated = 22,
        [Description("Invoice Fully Paid")]
        InvoiceFullyPaid = 23,
        [Description("Invoice Voided")]
        InvoiceVoided = 24,
        [Description("Contact Disabled")]
        ContactDisabled = 25,
        [Description("Transaction Created")]
        TransactionCreated = 26,
        [Description("Instant Payment Failed")]
        InstantPaymentFailed = 27,
        [Description("Communication Blockout Added")]
        CommunicationBlockoutAdded = 28,
        [Description("Communication Blockout Disabled")]
        CommunicationBlockoutDisabled = 29,
        [Description("Notification Send Blocked")]
        NotificationSendBlocked = 30,
        [Description("Payment Blockout Added")]
        PaymentBlockoutAdded = 31,
        [Description("Payment Blockout Disabled")]
        PaymentBlockoutDisabled = 32,
        [Description("Payment Request Blocked")]
        PaymentRequestBlocked = 33,
        [Description("New Matter Created")]
        NewMatterCreated = 34,
        [Description("Matter Updated")]
        MatterUpdated = 35,
        [Description("SMS Opted Out")]
        SMSOptedOut = 36,
        [Description("SMS Opted In")]
        SMSOptedIn = 37,
        [Description("SMS Help Info Requested")]
        SMSHelpInfoRequested = 38,
        [Description("Payment Plan Updated")]
        PaymentPlanUpdated = 39,
    }
}
