// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum AnalyticEventType
    {
        ApplicationInitiated = 0,
        LocationChanged = 1,
        FieldChanged = 2,
        FrequencyChanged = 3,
        MenuClosed = 4,
        MenuOpen = 5,
        PaymentKeyUpdated = 6,
        EmailFieldChanged = 7,
        PasswordFieldChanged = 8,
        UserLoginSuccess = 9,
        UserLoginFailure = 10,
        FormClosed = 11,
        InvoiceRequest = 12,
        InvoiceSuccess = 13,
        InvoiceFailure = 14,
        PayNowScreenVisited = 15,
        PaymentPlanScreenVisited = 16,
        PaymentSubmitted = 17,
        CallbackRequested = 18,
        UserLogoutSuccess = 19,
        PaymentDetailsSubmitted = 20,
        HelpButtonClicked = 21,
        CallbackDateChanged = 22,
        CallbackTimeChanged = 23,
    }
}
