// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum BlockoutReason
    {
        Unknown = 0,
        Other = 10,
        Financial = 20,
        Medical = 30,
        Cease = 40,
        OptOut = 50,
        [Description("Email ptOut")]
        EmailOptOut = 51,
        [Description("SMS OptOut")]
        SMSOptOut = 52,
        Investigation = 60,
        PendingExternalPayment = 70,
        Complaint = 80,
        Dispute = 90,
    }
}
