// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum CallbackTime
    {
        [Description("Morning 9am-12pm")]
        Morning = 0,
        [Description("Afternoon 12pm-5pm")]
        Afternoon = 1,
        [Description("Night 5pm-9pm")]
        Night = 2,
    }
}
