// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum CampaignTagCategory
    {
        EtlTag = 1,
        StrategyTag = 2,
        ActivityTag = 3,
        AccountStatusTag = 4,
    }
}
