// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum CampaignTagCategory
    {
        EtlTag = 1,
        StrategyTag = 2,
        ActivityTag = 3,
        AccountStatusTag = 4,
    }
}
