// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum CardType
    {
        MasterCard = 1,
        Visa = 2,
        Amex = 3,
        None = 4,
    }
}
