// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum CardType
    {
        MasterCard = 1,
        Visa = 2,
        Amex = 3,
        None = 4,
    }
}
