// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum CommunicationTemplate
    {
        Unknown = 0,
        Policy = 1,
        [Description("Payment Success")]
        PaymentSuccess = 2,
        [Description("Payment Failed")]
        PaymentFailed = 3,
        Adhoc = 4,
        Callback = 5,
        Campaign = 6,
        [Description("Send Update Payment Details")]
        SendUpdatePaymentDetails = 7,
        [Description("Send Payment Reminder")]
        SendPaymentReminder = 8,
        [Description("Instant Payment Failed")]
        InstantPaymentFailed = 9,
        [Description("Payment Plan Payment Failed")]
        PaymentPlanPaymentFailed = 10,
        [Description("Payment Plan Started")]
        PaymentPlanStarted = 12,
        [Description("Payment Plan Updated")]
        PaymentPlanUpdated = 13,
        [Description("Payment Plan Cancelled")]
        PaymentPlanCancelled = 14,
        [Description("SMS Opt Out")]
        SMSOptOut = 15,
        [Description("SMS Opt In")]
        SMSOptIn = 16,
        [Description("SMS Help")]
        SMSHelp = 17,
        [Description("Payment Plan Started")]
        PaymentPlanOTFPStarted = 18,
        [Description("Payment Plan Updated")]
        PaymentPlanOTFPUpdated = 19,
        [Description("Payment Plan Cancelled")]
        PaymentPlanOTFPCancelled = 20,
    }
}
