// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum CommunicationGateway
    {
        [Description("Used as a placeholder when a creditor sends only Emails or SMS")]
        None = -1,
        [Description("Principle Email system")]
        SendGrid = 0,
        [Description("Principle SMS system")]
        Twilio = 1,
        [Description("Used for MMS messages")]
        Bandwidth = 2,
        Telgorithm = 3,
        SBT = 4,
    }
}
