// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum FeeType
    {
        [Description("Use for tiered recurring payment administration fee")]
        RepaymentAdministrationFee = 0,
    }
}
