// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum FeeType
    {
        [Description("Use for tiered recurring payment administration fee")]
        RepaymentAdministrationFee = 0,
    }
}
