// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum FileStateStatus
    {
        Unknown = 0,
        Processing = 1,
        Completed = 2,
        Error = 3,
    }
}
