// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum Industry
    {
        [Description("Debt Collector")]
        DebtCollector = 0,
        [Description("Telecom")]
        Telco = 1,
        Utility = 2,
        [Description("Service Provider")]
        ServiceProvider = 3,
        Medical = 4,
        [Description("Non-Bank Lender")]
        NonBankLender = 5,
        Tollways = 6,
    }
}
