// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum IntegrationType
    {
        Manual = 0,
        [Description("Spreadsheet")]
        Csv = 1,
        Xero = 2,
        Pioneer = 3,
        Api = 4,
        Storman = 5,
    }
}
