// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum NotificationType
    {
        [Description("SmsMMS")]
        Sms = 0,
        Email = 1,
        [Description("VM Drop")]
        VoiceMailDrop = 2,
        AIVoiceAgent = 3,
        ApiDirectLink = 4,
        Unknown = 5,
        MMS = 6,
    }
}
