// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum NotificationFailureReason
    {
        [Description("No Failure")]
        NoFailure = 0,
        [Description("Unknown Error")]
        UnknownError = 1,
        [Description("Unknown Number")]
        UnknownNumber = 2,
        [Description("Unreachable Number")]
        UnreachableNumber = 3,
        [Description("Landline Number")]
        LandlineNumber = 4,
        [Description("Carrier Violation")]
        CarrierViolation = 5,
        [Description("System Blocked")]
        SystemBlocked = 6,
        [Description("Invalid Request")]
        InvalidRequest = 7,
        Unauthorized = 8,
        Forbidden = 9,
        [Description("Unsupported Content Type")]
        UnsupportedContentType = 10,
        [Description("Max Message Queue Size Exceeded")]
        ExceedQueueMessage = 11,
    }
}
