// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum NotificationSendBlockedReason
    {
        Unknown = 0,
        CreditorIsNotActive = 10,
        CreditorSendPaymentPlanEmailReminderIsDisabled = 11,
        CreditorSendPaymentPlanSmsReminderIsDisabled = 12,
        CreditorSendUpdatePaymentMessageIsDisabled = 13,
        CreditorStateBasedSmsIsDisabled = 14,
        CreditorDisabledEmailNotification = 15,
        CreditorSendPaymentPlanTenDaysEmailReminderIsDisabled = 16,
        CreditorSendPaymentPlanTenDaysSmsReminderIsDisabled = 17,
        CreditorSendPaymentPlanThreeDaysEmailReminderIsDisabled = 18,
        CreditorSendPaymentPlanThreeDaysSmsReminderIsDisabled = 19,
        ContactIsNotActive = 20,
        ContactHasNoEmailAddress = 21,
        ContactHasNoMobileNumber = 22,
        InvoiceBlockoutPeriodIsInEffect = 30,
        TemplateDoesNotExist = 40,
        AutoStartCampaignScheduleCouldNotBeFound = 50,
        AutoStartCampaignStopped = 51,
        AutoStartCampaignIsArchived = 52,
        CampaignIsDeleted = 60,
        CampaignInvoiceNoLongerQualifies = 61,
        DirectPayment = 70,
    }
}
