// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum NotificationStatus
    {
        Sent = 0,
        Delivered = 1,
        Failed = 2,
        Opened = 3,
        Clicked = 4,
        Processed = 5,
        Queued = 6,
        [Description("Spam Report")]
        SpamReport = 7,
        Blocked = 8,
    }
}
