// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum PaymentType
    {
        [Description("EWay...")]
        EWay = 1,
        PayPal = 2,
        [Description("Direct Deposit")]
        DirectDeposit = 3,
        [Description("External System")]
        ExternalSystem = 4,
        [Description("Bank Transfer")]
        BankTransfer = 5,
        BPay = 6,
        [Description("Credit Card")]
        CreditCard = 7,
        [Description("Debit Card")]
        DebitCard = 8,
        [Description("Gateway Down")]
        GatewayDown = 10,
        PayWayCreditCard = 11,
        PayWayBankAccount = 12,
        [Description("BPoint Credit Card")]
        BPointCreditCard = 13,
        [Description("BPoint Bank Account")]
        BPointBankAccount = 14,
        [Description("Ezidebit Credit Card")]
        EzidebitCreditCard = 15,
        [Description("Ezidebit Debit Card")]
        EzidebitDebitCard = 16,
        [Description("Ezidebit Bank Account")]
        EzidebitBankAccount = 17,
        [Description("MCPayment Credit Card")]
        MCPaymentCreditCard = 18,
        SecurePayCreditCard = 19,
        SecurePayBankAccount = 20,
        FatZebraCreditCard = 21,
        StripeCreditCard = 22,
        StripeBankAccount = 23,
        BraintreeCreditCard = 24,
        [Description("ACH Account")]
        AliaswireACHAccount = 25,
        [Description("Debit Card")]
        AliaswireCreditCard = 26,
        [Description("ACH Account")]
        EpicPayACHAccount = 27,
        [Description("Debit Card")]
        EpicPayDebitCard = 28,
        [Description("Credit Card")]
        EpicPayCreditCard = 29,
        [Description("Debit Card")]
        CreditNinjaDebitCard = 32,
        [Description("ACH Account")]
        RepayACH = 33,
        [Description("Debit Card")]
        RepayCard = 34,
        [Description("ACH Account")]
        DirectACH = 35,
        [Description("ACH Account")]
        WestlakeACH = 36,
        [Description("Debit Card")]
        WestlakeDebitCard = 37,
        [Description("Credit Card")]
        WestlakeCreditCard = 38,
        [Description("Credit Card")]
        AcimaCreditCard = 39,
        [Description("Credit Card")]
        AcimaCreditCardSif = 43,
        [Description("Credit Card")]
        AcimaSettlementCard = 44,
        [Description("Debit Card")]
        LoanPaymentProDebitCard = 45,
        [Description("Credit Card")]
        LoanPaymentProCreditCard = 46,
        [Description("ACH Account")]
        ACH = 47,
        [Description("Credit Card")]
        PayixCreditCard = 48,
        [Description("Debit Card")]
        PayixDebitCard = 49,
        [Description("Credit Card")]
        NMICreditCard = 50,
        [Description("Debit Card")]
        NMIDebitCard = 51,
        [Description("Credit Card")]
        FluidPayCreditCard = 52,
        [Description("Debit Card")]
        FluidPayDebitCard = 53,
        [Description("Credit Card")]
        PDCFlowCreditCard = 54,
        [Description("Debit Card")]
        PDCFlowDebitCard = 55,
        [Description("ACH Account")]
        CarmelSolutionsACH = 56,
        [Description("Credit Card")]
        FortisCreditCard = 57,
        [Description("Debit Card")]
        FortisDebitCard = 58,
        [Description("ACH Account")]
        RepayACHV2 = 59,
        [Description("Debit Card")]
        RepayDebitCardV2 = 60,
        [Description("Credit Card")]
        RepayCreditCardV2 = 61,
        [Description("Credit Card")]
        BraviantDebitCard = 62,
        [Description("Debit Card")]
        BraviantCreditCard = 63,
        [Description("ACH Account")]
        BraviantACH = 64,
        [Description("Credit Card")]
        ValmarCreditCard = 65,
        [Description("Debit Card")]
        ValmarDebitCard = 66,
        [Description("Credit Card")]
        NMICreditCardV2 = 67,
        [Description("Debit Card")]
        NMIDebitCardV2 = 68,
        [Description("Credit Card")]
        NuveiCreditCard = 69,
        [Description("Debit Card")]
        NuveiDebitCard = 70,
        [Description("ACH Account")]
        NuveiACH = 71,
        [Description("ACH Account")]
        ValmarACH = 72,
        [Description("Credit Card")]
        AuthNetCredit = 73,
        [Description("Debit Card")]
        AuthNetDebit = 74,
        [Description("ACH Account")]
        AuthNetACH = 75,
        [Description("Debit Card")]
        BraviantDebitV2 = 76,
        [Description("Credit Card")]
        BraviantCreditV2 = 77,
        [Description("ACH Account")]
        BraviantACHV2 = 78,
        [Description("Debit Card")]
        LoanPaymentProDebitV2 = 79,
        [Description("Credit Card")]
        LoanPaymentProCreditV2 = 80,
        [Description("ACH Account")]
        LoanPaymentProACHV2 = 81,
        [Description("Debit Card")]
        ACISpeedpayDebit = 82,
        [Description("Credit Card")]
        ACISpeedpayCredit = 83,
        [Description("ACH Account")]
        ACISpeedpayACH = 84,
        [Description("Debit Card")]
        RepayCardAdvanceAmerica = 85,
        [Description("Debit Card")]
        RACPaymentDebit = 86,
        [Description("Credit Card")]
        RACPaymentCredit = 87,
        [Description("ACH Account")]
        RACPaymentACH = 88,
        [Description("Debit Card")]
        AcceptanceNowPaymentDebit = 89,
        [Description("Credit Card")]
        AcceptanceNowPaymentCredit = 90,
        [Description("ACH Account")]
        AcceptanceNowPaymentACH = 91,
        [Description("Debit Card")]
        TestRACPaymentDebit = 92,
        [Description("Credit Card")]
        TestRACPaymentCredit = 93,
        [Description("ACH Account")]
        TestRACPaymentACH = 94,
        [Description("Debit Card")]
        PayliancePaymentDebit = 95,
        [Description("Credit Card")]
        PayliancePaymentCredit = 96,
        [Description("ACH Account")]
        PayliancePaymentACH = 97,
        [Description("Debit Card")]
        PropelHoldingsLPPDebitCard = 98,
        [Description("Credit Card")]
        PropelHoldingsLPPCreditCard = 99,
        [Description("ACH Account")]
        PropelHoldingsLPPACH = 100,
        [Description("Debit Card")]
        MoneyKeyRepayDebit = 101,
        [Description("Credit Card")]
        MoneyKeyRepayCredit = 102,
        [Description("ACH Account")]
        MoneyKeyRepayACH = 103,
        [Description("Debit Card")]
        USIOPaymentDebit = 104,
        [Description("Credit Card")]
        USIOPaymentCredit = 105,
        [Description("ACH Account")]
        USIOPaymentACH = 106,
        [Description("Debit Card")]
        PllentyPaymentDebit = 107,
        [Description("Credit Card")]
        PllentyPaymentCredit = 108,
        [Description("ACH Account")]
        PllentyPaymentACH = 109,
        [Description("Debit Card")]
        RepayCardDCA = 113,
        [Description("Debit Card")]
        RepayMoneytree = 114,
        [Description("DebitCard")]
        CardConnectDebit = 115,
        [Description("Credit Card")]
        CardConnectCredit = 116,
        [Description("ACH Account")]
        CardConnectACH = 117,
        [Description("Debit Card")]
        ChannelPaymentDebit = 118,
        [Description("Credit Card")]
        ChannelPaymentCredit = 119,
        [Description("ACH Account")]
        ChannelPaymentACH = 120,
        [Description("Debit Card")]
        OmniaPayDebit = 121,
        [Description("Credit Card")]
        OmniaPayCredit = 122,
        [Description("ACH Account")]
        OmniaPayACH = 123,
        [Description("Debit Card")]
        AcimaPayoffCard = 124,
        [Description("Debit Card")]
        USAePayDebit = 125,
        [Description("Credit Card")]
        USAePayCredit = 126,
        [Description("ACH Account")]
        USAePayACH = 127,
        [Description("Debit Card")]
        SnapFinanceLoanProDebit = 128,
        [Description("Credit Card")]
        SnapFinanceLoanProCredit = 129,
        [Description("ACH Account")]
        SnapFinanceLoanProACH = 130,
        [Description("Debit Card")]
        RepayCardMoneyMartUS = 131,
        [Description("Debit Card")]
        RepayCardMoneyMartCAN = 132,
        [Description("Card")]
        AcimaPaymentPlan = 133,
        [Description("Card")]
        AcimaSettlementPaymentPlan = 134,
        [Description("Debit Card")]
        PayrocDebit = 135,
        [Description("CreditCard")]
        PayrocCredit = 136,
        [Description("ACH Account")]
        PayrocACH = 137,
        [Description("Debit Card")]
        PowerFinanceTexasRepayCard = 138,
        [Description("Debit Card")]
        MoneyStashRepayCard = 139,
    }
}
