// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum PaymentFrequency
    {
        Weekly = 0,
        Fortnightly = 1,
        Monthly = 2,
        Daily = 3,
        OneTimeFullPayment = 4,
        Custom = 5,
        SemiMonthly = 6,
    }
}
