// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum PaymentStatus
    {
        Submitted = 10,
        Pending = 20,
        Declined = 30,
        Paid = 40,
        Deleted = 50,
        Blocked = 60,
        ACHSubmitted = 90,
        NetworkError = 100,
        ClientManualUpdate = 110,
    }
}
