// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum PaymentSyncStatus
    {
        [Description("Awaiting Sync")]
        AwaitingSync = 0,
        [Description("Conflicted Sync")]
        ConflictedSync = 1,
        Synced = 2,
    }
}
