// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum PaymentPlanCancelReason
    {
        Unknown = 0,
        Paid = 2,
        Voided = 3,
        Defaulted = 4,
        Closed = 5,
        [Description("Client Requested")]
        ClientRequested = 6,
        [Description("Customer Requested")]
        CustomerRequested = 7,
        [Description("Failed Payment Retry Exhausted")]
        FailedPaymentRetryExhausted = 8,
        [Description("Final Arrangement Date Due Triggered")]
        FinalArrangementDateDueTriggered = 9,
        [Description("Scheduled Payments Completed")]
        ScheduledPaymentsCompleted = 10,
        [Description("Failed Recurring Payment Threshold Reached")]
        FailedRecurringPaymentThresholdReached = 11,
    }
}
