// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum PaymentGateway
    {
        Repay = 1,
        FluidPay = 2,
        Braviant = 3,
        Nuvei = 4,
        EpicPay = 5,
        Payroc = 6,
        Channel = 7,
    }
}
