// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum PayPalReasonCode
    {
        [Description("Charge Back")]
        CHARGEBACK = 0,
        [Description("Guarantee")]
        GUARANTEE = 1,
        [Description("Buyer Complaint")]
        BUYERCOMPLAINT = 2,
        [Description("Refund")]
        REFUND = 3,
        [Description("Unconfirmed Shipping Address")]
        UNCONFIRMEDSHIPPINGADDRESS = 4,
        [Description("E-Check")]
        ECHECK = 5,
        [Description("International Withdrawal")]
        INTERNATIONALWITHDRAWAL = 6,
        [Description("Receiving Preference Mandates Manual Action")]
        RECEIVINGPREFERENCEMANDATESMANUALACTION = 7,
        [Description("Payment Review")]
        PAYMENTREVIEW = 8,
        [Description("Regulatory Review")]
        REGULATORYREVIEW = 9,
        [Description("Unilateral")]
        UNILATERAL = 10,
        [Description("Verification Required")]
        VERIFICATIONREQUIRED = 11,
        [Description("Transaction Approved Awaiting Funding")]
        TRANSACTIONAPPROVEDAWAITINGFUNDING = 12,
    }
}
