// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum PayPalTransactionState
    {
        [Description("Pending")]
        Pending = 0,
        [Description("Completed")]
        Completed = 1,
        [Description("Refunded")]
        Refunded = 2,
        [Description("Partially Refunded")]
        PartiallyRefunded = 3,
    }
}
