// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum PhoneType
    {
        [Description("Direct Dial")]
        DirectDial = 0,
        Mobile = 1,
        Other = 2,
    }
}
