// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum PhoneType
    {
        [Description("Direct Dial")]
        DirectDial = 0,
        Mobile = 1,
        Other = 2,
    }
}
