// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum PlaybookStrategy
    {
        [Description("Does not use schedule")]
        PlaybookStrategyDays = 0,
        [Description("Uses schedules")]
        PlaybookStrategySteps = 1,
    }
}
