// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum PlaybookStrategy
    {
        [Description("Does not use schedule")]
        PlaybookStrategyDays = 0,
        [Description("Uses schedules")]
        PlaybookStrategySteps = 1,
    }
}
