// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum PolicyStatus
    {
        Inactive = 0,
        Active = 1,
        Triggered = 2,
        Sent = 3,
        Paid = 4,
    }
}
