// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum RepayCustomIntegration
    {
        Default = 0,
        AdvanceAmerica = 1,
        MoneyStash = 2,
        MoneyTree = 3,
        MoneymartUS = 4,
        MoneymartCA = 5,
        RepayDCA = 6,
        RepayV2 = 7,
        AF247 = 8,
    }
}
