// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum ScheduleCommunicationPreference
    {
        None = 0,
        UserPreference = 1,
        OppositeToUserPreference = 2,
        Sms = 3,
        Email = 4,
        Facebook = 5,
        Both = 6,
        [Description("User Preference - Defaults to SMS when no preference")]
        UserPreferenceWithDefaultSms = 7,
        VoiceMailDrop = 8,
    }
}
