// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum ScheduleStatus
    {
        Scheduled = 0,
        CompletedWithError = 1,
        CompletedWithWarning = 2,
        CompletedSuccessfully = 3,
        Cancelled = 4,
    }
}
