// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum SettlementType
    {
        [Description("Balance based settlement")]
        Balance = 1,
        [Description("Duration based settlement")]
        Duration = 2,
    }
}
