// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum SmsPlatform
    {
        Twilio = 0,
        Bandwidth = 1,
        Telgorithm = 2,
        SBT = 3,
    }
}
