// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Enums.ReferenceData
{
    public enum SmsPlatform
    {
        Twilio = 0,
        Bandwidth = 1,
        Telgorithm = 2,
        SBT = 3,
    }
}
