// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using System.ComponentModel;

namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum Source
    {
        [Description("An end user")]
        User = 0,
        [Description("Engine system")]
        Engine = 1,
        [Description("The Payment Portal")]
        PaymentPortal = 2,
        [Description("The Creditor Portal")]
        CreditorPortal = 3,
        [Description("Twilio Callback")]
        Twilio = 4,
        [Description("SendGrid Callback")]
        SendGrid = 5,
        ReachTEL = 6,
        [Description("Bandwidth Callback")]
        Bandwidth = 7,
        [Description("Telgorithm Callback")]
        Telgorithm = 8,
        [Description("SBT Callback")]
        SBTEngine = 9,
        [Description("Bandwidth Outbound Webhook")]
        BandwidthOutbound = 10,
        [Description("Bandwidth Inbound Webhook")]
        BandwidthInbound = 11,
        [Description("Telgorithm Outbound Webhook")]
        TelgorithmOutbound = 12,
        [Description("Telgorithm Inbound Webhook")]
        TelgorithmInbound = 13,
        [Description("SBT Outbound Webhook")]
        SBTOutbound = 14,
        [Description("SBT Inbound Webhook")]
        SBTInbound = 15,
        [Description("DropCowboy Callback")]
        DropCowboy = 16,
    }
}
