// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum TransactionType
    {
        Charge = 0,
        AdHocPayment = 1,
        RecurringPayment = 2,
        UpfrontPayment = 3,
        DirectPayment = 4,
        PartialPayment = 5,
    }
}
