// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum TwilioEvent
    {
        Accepted = 0,
        Queued = 1,
        Sending = 2,
        Sent = 3,
        Receiving = 4,
        Received = 5,
        Delivered = 6,
        Undelivered = 7,
        Failed = 8,
    }
}
