// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ReferenceData
{
    public enum VMPlatform
    {
        TESTDropCowboy = 0,
        DropCowboyNew = 5,
        DropCowboy = 6,
    }
}
