// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.ETL
{
    [Table("ETL.CreditorCommitSummary")]
    public class CreditorCommitSummary
    {
        [Key]
        public int Id { get; set; }
        public string CommitSummaryKey { get; set; }
        public string CreditorId { get; set; }
        public DateTime ProcessStartTime { get; set; }
        public string? DataIngestionKey { get; set; }
        public string FileNames { get; set; }
        public int InvoiceCount { get; set; }
        public int ContactsCount { get; set; }
        public int PaymentsCount { get; set; }
        public int MetaDataCount { get; set; }
        public int NetNewInvoicesCount { get; set; }
        public int VoidedInvoicesCount { get; set; }
        public int InvoicesUpdatedCount { get; set; }
        public decimal TotalInvoice { get; set; }
        public decimal AverageDaysPastDue { get; set; }
        public string? ErrorsOrWarnings { get; set; }
        public int TotalNewMattersUploaded { get; set; }
    }
}
