// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.ETL
{
    [Table("ETL.DataSourceField")]
    public class DataSourceField
    {
        public int DataSourceFieldId { get; set; }
        [Key]
        public int DataFieldMappingId { get; set; }
        public int DataSourceFieldMappingTypeId { get; set; }
        public string Name { get; set; }
        public string? ConstantValue { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
