// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.ETL
{
    [Table("ETL.FieldMappingValue")]
    public class FieldMappingValue
    {
        [Key]
        public int FieldMappingValueId { get; set; }
        public int DataSourceFieldId { get; set; }
        public string SourceValue { get; set; }
        public string TargetValue { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
