// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.ETL
{
    [Table("ETL.FileState")]
    public class FileState
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string FileName { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? CompletedDate { get; set; }
        public int FileStateStatus { get; set; }
    }
}
