// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.ETL
{
    [Table("ETL.Hash")]
    public class Hash
    {
        public string Key { get; set; }
        public string Field { get; set; }
        public string? Value { get; set; }
        public DateTime? ExpireAt { get; set; }
        // NOTE: Composite primary key detected; use EF Core Fluent API to configure:
        // modelBuilder.Entity<Hash>().HasKey(e => new { /* add key parts here */ });
    }
}
