// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.ETL
{
    [Table("ETL.IngestionResult")]
    public class IngestionResult
    {
        [Key]
        public int IngestionResultId { get; set; }
        public int CreditorId { get; set; }
        public DateTime ProcessStartTime { get; set; }
        public DateTime? ProcessFinishTime { get; set; }
        public string FileNames { get; set; }
        public int TotalProcessedRecordCount { get; set; }
        public int InvoiceCount { get; set; }
        public int ContactCount { get; set; }
        public int PaymentCount { get; set; }
        public int MetaDataCount { get; set; }
        public int InvoiceConfigCount { get; set; }
        public int VoidedInvoiceCount { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public string? EtlIds { get; set; }
        public string? CompletionMessage { get; set; }
    }
}
