// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.ETL
{
    [Table("ETL.JobParameter")]
    public class JobParameter
    {
        public long JobId { get; set; }
        public string Name { get; set; }
        public string? Value { get; set; }
        // NOTE: Composite primary key detected; use EF Core Fluent API to configure:
        // modelBuilder.Entity<JobParameter>().HasKey(e => new { /* add key parts here */ });
    }
}
