// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.ETL
{
    [Table("ETL.JobQueue")]
    public class JobQueue
    {
        public long Id { get; set; }
        public long JobId { get; set; }
        public string Queue { get; set; }
        public DateTime? FetchedAt { get; set; }
        // NOTE: Composite primary key detected; use EF Core Fluent API to configure:
        // modelBuilder.Entity<JobQueue>().HasKey(e => new { /* add key parts here */ });
    }
}
