// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.ETL
{
    [Table("ETL.List")]
    public class List
    {
        public long Id { get; set; }
        public string Key { get; set; }
        public string? Value { get; set; }
        public DateTime? ExpireAt { get; set; }
        // NOTE: Composite primary key detected; use EF Core Fluent API to configure:
        // modelBuilder.Entity<List>().HasKey(e => new { /* add key parts here */ });
    }
}
