// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.ETL
{
    [Table("ETL.Schema")]
    public class Schema
    {
        [Key]
        public int Version { get; set; }
    }
}
