// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.ETL
{
    [Table("ETL.Server")]
    public class Server
    {
        [Key]
        public string Id { get; set; }
        public string? Data { get; set; }
        public DateTime LastHeartbeat { get; set; }
    }
}
