// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Billing
{
    [Table("Billing.Client")]
    public class Client
    {
        [Key]
        public int ClientId { get; set; }
        public string? CompanyName { get; set; }
        public string? StreetAddress { get; set; }
        public string? City { get; set; }
        public string? StateAbbr { get; set; }
        public string? PostalCode { get; set; }
        public string? Country { get; set; }
        public string RecientToFullName { get; set; }
        public int TermsDays { get; set; }
        public int? MonthlyMinimum { get; set; }
        public int CallbackRange { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
