// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Views
{
    public class ViewTemplate
    {
        public string Name { get; set; }
        public DateTime? ArchivedOn { get; set; }
        public string? TemplateId { get; set; }
        public string CreditorId { get; set; }
    }
}
