// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Views
{
    public class ViewTemplate
    {
        public string Name { get; set; }
        public DateTime? ArchivedOn { get; set; }
        public string? TemplateId { get; set; }
        public string CreditorId { get; set; }
    }
}
