// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Logging
{
    [Table("Logging.BandwidthWebhookRequestPayloads")]
    public class BandwidthWebhookRequestPayloads
    {
        [Key]
        public int Id { get; set; }
        public string? CreditorId { get; set; }
        public string? SmsSid { get; set; }
        public string? Payload { get; set; }
        public int? Source { get; set; }
        public DateTime? ReceivedOn { get; set; }
    }
}
