// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Logging
{
    [Table("Logging.EndpointRequest")]
    public class EndpointRequest
    {
        [Key]
        public int EndpointRequestId { get; set; }
        public string ApiName { get; set; }
        public string MachineName { get; set; }
        public string Verb { get; set; }
        public string Scheme { get; set; }
        public string Host { get; set; }
        public int PortNumber { get; set; }
        public string UrlPath { get; set; }
        public string? QueryString { get; set; }
        public string? Headers { get; set; }
        public string? Payload { get; set; }
        public int? ResponseStatusCode { get; set; }
        public string? ResponseBody { get; set; }
        public int? DurationMs { get; set; }
        public string? CorrelationId { get; set; }
        public string? UserId { get; set; }
        public string? IpAddress { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
