// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Logging
{
    [Table("Logging.ExpectedScheduledPayments")]
    public class ExpectedScheduledPayments
    {
        [Key]
        public int Id { get; set; }
        public string? InvoiceId { get; set; }
        public string? CreditorId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? ScheduledDate { get; set; }
        public decimal? Amount { get; set; }
        public bool? SentByServiceBus { get; set; }
    }
}
