// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Logging
{
    [Table("Logging.PaymentGatewayAttemptFailure")]
    public class PaymentGatewayAttemptFailure
    {
        [Key]
        public int Id { get; set; }
        public string? CreditorId { get; set; }
        public string? InvoiceId { get; set; }
        public string? EventSource { get; set; }
        public string? FailureResponse { get; set; }
        public DateTime? CreatedOn { get; set; }
    }
}
