// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Logging
{
    [Table("Logging.PaymentPortalCardTokenizationAttempt")]
    public class PaymentPortalCardTokenizationAttempt
    {
        [Key]
        public long Id { get; set; }
        public int CreditorId { get; set; }
        public string AccountInvoiceNumber { get; set; }
        public int PaymentTypeId { get; set; }
        public string Method { get; set; }
        public string Url { get; set; }
        public string? Payload { get; set; }
        public string? ResponseText { get; set; }
        public bool Status { get; set; }
        public DateTime CreatedOnUtc { get; set; }
    }
}
