// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Logging
{
    [Table("Logging.PaymentGatewayHttpCall")]
    public class PaymentGatewayHttpCall
    {
        public int Id { get; set; }
        public string? TransactionCorrelationId { get; set; }
        public string? AccountInvoiceId { get; set; }
        public string? CreditorId { get; set; }
        public int PaymentType { get; set; }
        public string? RawRequest { get; set; }
        public string? RawResponse { get; set; }
        public DateTime CreatedOn { get; set; }
        public string? CreatedBy { get; set; }
    }
}
