// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Logging
{
    [Table("Logging.SmsGatewayFailureRequest")]
    public class SmsGatewayFailureRequest
    {
        [Key]
        public int Id { get; set; }
        public string? CreditorId { get; set; }
        public string? Request { get; set; }
        public string? Payload { get; set; }
        public int? Source { get; set; }
        public DateTime? SubmittedOn { get; set; }
    }
}
