// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Views.Maintenance
{
    public class AzureSqlMaintenanceLogView
    {
        public long SqlMaintenanceLogId { get; set; }
        public DateTime? OperationTime { get; set; }
        public string? SchemaName { get; set; }
        public string? TableName { get; set; }
        public string? IndexName { get; set; }
        public string? CommandText { get; set; }
        public string? ExtraInfo { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public TimeSpan? JobDuration { get; set; }
        public string? StatusMessage { get; set; }
    }
}
