// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Views.Maintenance
{
    public class IndexFragmentationView
    {
        public string SchemaName { get; set; }
        public string TableName { get; set; }
        public string? IndexName { get; set; }
        public double? AvgFragmentationPercent { get; set; }
        public long? FragmentCount { get; set; }
        public double? AvgFragmentPages { get; set; }
        public short? DatabaseId { get; set; }
        public int? ObjectId { get; set; }
        public int? IndexId { get; set; }
        public int? PartitionNumber { get; set; }
        public string? IndexTypeDesc { get; set; }
        public string? AllocUnitTypeDesc { get; set; }
        public byte? IndexDepth { get; set; }
        public byte? IndexLevel { get; set; }
        public double? AvgFragmentationInPercent { get; set; }
        //public long? FragmentCount { get; set; }
        public double? AvgFragmentSizeInPages { get; set; }
        public long? PageCount { get; set; }
        public double? AvgPageSpaceUsedInPercent { get; set; }
        public long? RecordCount { get; set; }
        public long? GhostRecordCount { get; set; }
        public long? VersionGhostRecordCount { get; set; }
        public int? MinRecordSizeInBytes { get; set; }
        public int? MaxRecordSizeInBytes { get; set; }
        public double? AvgRecordSizeInBytes { get; set; }
        public long? ForwardedRecordCount { get; set; }
        public long? CompressedPageCount { get; set; }
        public long? HobtId { get; set; }
        public byte? ColumnstoreDeleteBufferState { get; set; }
        public string? ColumnstoreDeleteBufferStateDesc { get; set; }
        public long? VersionRecordCount { get; set; }
        public long? InrowVersionRecordCount { get; set; }
        public long? InrowDiffVersionRecordCount { get; set; }
        public long? TotalInrowVersionPayloadSizeInBytes { get; set; }
        public long? OffrowRegularVersionRecordCount { get; set; }
        public long? OffrowLongTermVersionRecordCount { get; set; }
    }
}
