// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Views.Accounts
{
    public class LegacyIdInvoiceContactView
    {
        public int AccountInvoiceId { get; set; }
        public string AccountInvoiceLegacyId { get; set; }
        public int AccountContactId { get; set; }
        public string AccountContactLegacyId { get; set; }
    }
}
