// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Views.Accounts
{
    public class LegacyIdInvoiceContactView
    {
        public int AccountInvoiceId { get; set; }
        public string AccountInvoiceLegacyId { get; set; }
        public int AccountContactId { get; set; }
        public string AccountContactLegacyId { get; set; }
    }
}
