// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using System.ComponentModel;

namespace Remitter.Models.Sql.Main.Enums.Maintenance
{
    public enum ManagedFunctionType
    {
        [Description("Copies data from one SQL Server table to another SQL server table")]
        DataCopySqlToSqlFunction = 1,
        [Description("Copies data from one SQL Server table to an Azure storage account data lake table")]
        DataCopySqlToDatalakeFunction = 2,
        [Description("Deletes (purges) data from a SQL Server table")]
        DataPurgeSqlFuction = 3,
    }
}
