// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Accounts
{
    [Table("Accounts.AccountInvoiceMetaData")]
    public class AccountInvoiceMetaData
    {
        [Key]
        public int Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public string MetaDataName { get; set; }
        public string? MetaDataValue { get; set; }
    }
}
