// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.AccountInvoiceTagHistory")]
    public class AccountInvoiceTagHistory
    {
        [Key]
        public long AccountInvoiceTagHistoryId { get; set; }
        public int CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string TagTypeName { get; set; }
        public string? TagValue { get; set; }
        public DateTime TagAssignedOnUtc { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? ExpireAfterUtc { get; set; }
    }
}
