// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Accounts
{
    [Table("Accounts.AccountInvoiceJournal")]
    public class AccountInvoiceJournal
    {
        [Key]
        public int Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public string CreditorId { get; set; }
        public string EntryId { get; set; }
        public string EntryType { get; set; }
        public string CorrelationId { get; set; }
        public decimal Amount { get; set; }
        public DateTime TransactionDate { get; set; }
        public string? Notes { get; set; }
    }
}
