// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Accounts
{
    [Table("Accounts.AccountContact")]
    public class AccountContact
    {
        [Key]
        public int Id { get; set; }
        public string AccountContactId { get; set; }
        public bool IsActive { get; set; }
        public string? CompanyName { get; set; }
        public int? IntegrationType { get; set; }
        public string IntegrationLinkId { get; set; }
        public string? ContactNumber { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? EmailAddress { get; set; }
        public string? SkypeUserName { get; set; }
        public string? BankAccountDetails { get; set; }
        public string? TaxNumber { get; set; }
        public string? DefaultCurrency { get; set; }
        public string? Website { get; set; }
        public string? AccountNumber { get; set; }
        public string? MostRecentSyncDocument { get; set; }
        public string CreditorId { get; set; }
        public string? MobileNumber { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? DeletedOn { get; set; }
        public string? FullName { get; set; }
        public string? TimeZone { get; set; }
        [Computed]
        public string? Name { get; set; }
    }
}
