// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.AccountContactMetaData")]
    public class AccountContactMetaData
    {
        [Key]
        public int Id { get; set; }
        public string AccountContactId { get; set; }
        public string MetaDataName { get; set; }
        public string? MetaDataValue { get; set; }
    }
}
