// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Accounts
{
    [Table("Accounts.AccountContactHistory")]
    public class AccountContactHistory
    {
        [Key]
        public int Id { get; set; }
        public string AccountContactId { get; set; }
        public string? MobileNumber { get; set; }
        public string? EmailAddress { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}
