// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.AccountInvoiceActivityTag")]
    public class AccountInvoiceActivityTag
    {
        [Key]
        public int AccountInvoiceActivityTagId { get; set; }
        public string AccountInvoiceId { get; set; }
        public int CreditorId { get; set; }
        public DateTime? AccountCurrentlyEngagedUtc { get; set; }
        public DateTime? AccountActivityUtc { get; set; }
        public DateTime? CallbackRequestedUtc { get; set; }
        public DateTime? LinkClickedUtc { get; set; }
        public DateTime? PartialPaymentViewedUtc { get; set; }
        public DateTime? PaymentPlanViewedUtc { get; set; }
        public DateTime? PayNowViewedUtc { get; set; }
        public string? LastMatterSyncDocId { get; set; }
        public DateTime? LastUpdateForMatterSyncDocUtc { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
        public int? AccountInvoiceTableId { get; set; }
        public DateTime? SpamReportReceivedUtc { get; set; }
        public DateTime? UnsubscribedReceivedUtc { get; set; }
        public DateTime? MessageOpenedUtc { get; set; }
    }
}
