// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Accounts
{
    [Table("Accounts.AccountInvoice")]
    public class AccountInvoice
    {
        [Key]
        public int Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public string ContactId { get; set; }
        public int Status { get; set; }
        public int IntegrationType { get; set; }
        public string? IntegrationLinkId { get; set; }
        public DateTime IssueDate { get; set; }
        public DateTime DueDate { get; set; }
        public decimal InterestRate { get; set; }
        public decimal InterestIncurred { get; set; }
        public decimal DebtPrincipal { get; set; }
        public decimal Total { get; set; }
        public decimal TotalDiscount { get; set; }
        public string CurrencyCode { get; set; }
        public decimal CurrencyRate { get; set; }
        public decimal AmountDue { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal AmountCredited { get; set; }
        public string? Url { get; set; }
        public string? Reference { get; set; }
        public string? MostRecentSyncDocument { get; set; }
        public bool UserDismissed { get; set; }
        public string CreditorId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? DeletedOn { get; set; }
        public DateTime? FullyPaidOnDate { get; set; }
        public decimal UpfrontAmount { get; set; }
        public string? IntegrationExternalLink { get; set; }
        public bool? EligibleForDiscount { get; set; }
        public string? DataField1 { get; set; }
        public string? DataField2 { get; set; }
        public string? DataField3 { get; set; }
        public string? DataField4 { get; set; }
        public string? DataField5 { get; set; }
        public string? DataField6 { get; set; }
        public string? DataField7 { get; set; }
        public string? DataField8 { get; set; }
        public string? DataField9 { get; set; }
        public string? DataField10 { get; set; }
        public string? DataField11 { get; set; }
        public string? DataField12 { get; set; }
        public string? DataField13 { get; set; }
        public string? DataField14 { get; set; }
        public string? DataField15 { get; set; }
        public string? DataField16 { get; set; }
        public string? DataField17 { get; set; }
        public string? DataField18 { get; set; }
        public string? DataField19 { get; set; }
        public string? DataField20 { get; set; }
        public string? RecurringTransactions { get; set; }
        public decimal? SettlementOfferAmount { get; set; }
    }
}
