// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.AccountInvoiceFee")]
    public class AccountInvoiceFee
    {
        [Key]
        public int Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public string FeeId { get; set; }
        public string FeeType { get; set; }
        public decimal FeeAmount { get; set; }
        public bool? IncludedInInterestCalculation { get; set; }
    }
}
