// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.AccountInvoiceVoidLog")]
    public class AccountInvoiceVoidLog
    {
        public string? Name { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }
}
