// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Accounts
{
    [Table("Accounts.ContactInfo")]
    public class ContactInfo
    {
        [Key]
        public int Id { get; set; }
        public string AccountContactId { get; set; }
        public string? ContactId { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? EmailAddress { get; set; }
    }
}
