// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Accounts
{
    [Table("Accounts.ContactPhone")]
    public class ContactPhone
    {
        [Key]
        public int Id { get; set; }
        public string AccountContactId { get; set; }
        public int? PhoneType { get; set; }
        public string? PhoneNumber { get; set; }
        public string? PhoneAreaCode { get; set; }
        public string? PhoneCountryCode { get; set; }
        public bool? IsMobile { get; set; }
    }
}
