// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.Document")]
    public class Document
    {
        [Key]
        public int Id { get; set; }
        public string? CreditorId { get; set; }
        public string? IntegrationLinkId { get; set; }
        public string? FileName { get; set; }
        public string? BlobUrl { get; set; }
        public string? UploadedBy { get; set; }
        public DateTime? UploadDate { get; set; }
    }
}
