// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.InvoiceActivities")]
    public class InvoiceActivities
    {
        [Key]
        public int Id { get; set; }
        public int AccountInvoiceId { get; set; }
        public int? NotificationTypeId { get; set; }
        public int? CommunicationTemplateId { get; set; }
        public int ActivityTypeId { get; set; }
        public DateTime ActivityDate { get; set; }
        public string? MetaData { get; set; }
    }
}
