// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.InvoiceConfigOverride")]
    public class InvoiceConfigOverride
    {
        public int InvoiceConfigOverrideId { get; set; }
        public int CreditorId { get; set; }
        [Key]
        public string AccountInvoiceId { get; set; }
        public string? CompanyName { get; set; }
        public string? EmailLogo { get; set; }
        public string? MobileLogo { get; set; }
        public DateTime? FinalArrangementDate { get; set; }
        public bool? EnableSinglePayment { get; set; }
        public bool? EnableAttachments { get; set; }
        public bool? EnablePaymentPlans { get; set; }
        public bool? EnablePartialPayment { get; set; }
        public double? MinimumAllowablePartialAmount { get; set; }
        public int? CreditCardGateWay { get; set; }
        public int? DebitCardGateWay { get; set; }
        public int? BankAccountGateWay { get; set; }
        public int? PaypalGateWay { get; set; }
        public bool? IsReauthorizationRequired { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
    }
}
