// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Accounts
{
    [Table("Accounts.InvoiceCampaignTag")]
    public class InvoiceCampaignTag
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string IntegrationLinkId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string CampaignTag { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string? Type { get; set; }
    }
}
