// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.InvoiceChallenge")]
    public class InvoiceChallenge
    {
        [Key]
        public int Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public int ChallengeType { get; set; }
        public string? ChallengeAnswer { get; set; }
    }
}
