// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Accounts
{
    [Table("Accounts.InvoiceReauthorization")]
    public class InvoiceReauthorization
    {
        [Key]
        public int InvoiceReauthorizationId { get; set; }
        public string AccountInvoiceId { get; set; }
        public int CreditorId { get; set; }
        public DateTime AcknowledgedOnUtc { get; set; }
        public DateTime? SignedOnUtc { get; set; }
        public string? IpAddress { get; set; }
        public string? NameSigned { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
    }
}
