// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.SettlementPaymentSetting")]
    public class SettlementPaymentSetting
    {
        public int Id { get; set; }
        public int CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public int? TransectionType { get; set; }
        public int Frequency { get; set; }
        public decimal SettlementPercentage { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime UpdatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
