// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Accounts
{
    [Table("Accounts.TokenizedWallet")]
    public class TokenizedWallet
    {
        [Key]
        public int TokenizedWalletId { get; set; }
        public string? AccountContactId { get; set; }
        public string? TokenId { get; set; }
        public string? AccountType { get; set; }
        public string? AccountName { get; set; }
        public string? AccountNumber { get; set; }
        public string? ExpiryMonth { get; set; }
        public string? ExpiryYear { get; set; }
        public string? IssuerName { get; set; }
        public bool? IsActive { get; set; }
        public int? PaymentType { get; set; }
        public string? PostalCode { get; set; }
        public string? BsbNumber { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
    }
}
