// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Maintenance
{
    [Table("Maintenance.DataCopySqlToDatalakeFunction")]
    public class DataCopySqlToDatalakeFunction
    {
        public int DataCopySqlToDatalakeFunctionId { get; set; }
        [Key]
        public int ManagedFunctionId { get; set; }
        public string SourceSchemaName { get; set; }
        public string SourceTableName { get; set; }
        public string TargetTableName { get; set; }
        public int RetentionDays { get; set; }
        public int PerRunBatchSize { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string? DeletedBy { get; set; }
        public DateTime? DeletedOn { get; set; }
    }
}
