// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Maintenance
{
    [Table("Maintenance.DataCopySqlToSqlFunction")]
    public class DataCopySqlToSqlFunction
    {
        public int DataCopySqlToSqlFunctionId { get; set; }
        [Key]
        public int ManagedFunctionId { get; set; }
        public string SourceSchemaName { get; set; }
        public string SourceTableName { get; set; }
        public string TargetSchemaName { get; set; }
        public string TargetTableName { get; set; }
        public int RetentionDays { get; set; }
        public int PerRunBatchSize { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string? DeletedBy { get; set; }
        public DateTime? DeletedOn { get; set; }
    }
}
