// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Maintenance
{
    [Table("Maintenance.DisposableRow")]
    public class DisposableRow
    {
        [Key]
        public int DisposableRowId { get; set; }
        public int RowId { get; set; }
        public int SysSchemaId { get; set; }
        public int SysTableId { get; set; }
        public bool IsRemovalPaused { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}
