// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Maintenance
{
    [Table("Maintenance.ManagedFunction")]
    public class ManagedFunction
    {
        [Key]
        public int ManagedFunctionId { get; set; }
        public int ManagedFunctionTypeId { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }
        public bool IsDisabled { get; set; }
        public string CronTriggerExpression { get; set; }
        public DateTime? LastStartDateTime { get; set; }
        public DateTime? LastFinishDateTime { get; set; }
        [Computed]
        public TimeSpan? Duration { get; set; }
        [Computed]
        public bool? IsRunning { get; set; }
        public DateTime? NextRunDateTime { get; set; }
        [Computed]
        public bool? IsDue { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string? DeletedBy { get; set; }
        public DateTime? DeletedOn { get; set; }
    }
}
