// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Maintenance
{
    [Table("Maintenance.ManagedDataFunctionEvent")]
    public class ManagedDataFunctionEvent
    {
        [Key]
        public int ManagedDataFunctionEventId { get; set; }
        public int ManagedFunctionId { get; set; }
        public string SchemaName { get; set; }
        public string TableName { get; set; }
        public DateTime StartedDateTime { get; set; }
        public DateTime FinishedDateTime { get; set; }
        [Computed]
        public TimeSpan? Duration { get; set; }
        public int RowsCount { get; set; }
        public long MinRowId { get; set; }
        public long MaxRowId { get; set; }
        public string PreparationMessage { get; set; }
        public string CompletionMessage { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}
