// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Maintenance
{
    [Table("Maintenance.WebhookBatchSaveEvent")]
    public class WebhookBatchSaveEvent
    {
        [Key]
        public int WebhookBatchSaveEventId { get; set; }
        public string WebhookName { get; set; }
        public DateTime StartedOnUtc { get; set; }
        public DateTime? FinishedOnUtc { get; set; }
        public int IncomingEventsCount { get; set; }
        public int PartitionCount { get; set; }
        public string? PartitionList { get; set; }
        public string? MinUniqueMessageId { get; set; }
        public string? MaxUniqueMessageId { get; set; }
        public string? CompletionMessage { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
