// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.BlacklistedEmails")]
    public class BlacklistedEmails
    {
        [Key]
        public long BlacklistedEmailId { get; set; }
        public int CreditorId { get; set; }
        public int AccountInvoiceId { get; set; }
        public string Email { get; set; }
        public string Reason { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
