// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.BlacklistedMobileNumbers")]
    public class BlacklistedMobileNumbers
    {
        [Key]
        public long BlackListedMobileNumberId { get; set; }
        public int CreditorId { get; set; }
        public int AccountInvoiceId { get; set; }
        public string MobileNumber { get; set; }
        public string Reason { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
