// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.Blockout")]
    public class Blockout
    {
        [Key]
        public Guid Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public DateTime From { get; set; }
        public DateTime To { get; set; }
        public string? Description { get; set; }
        public int Reason { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public bool Disabled { get; set; }
        public string? DisabledBy { get; set; }
        public DateTime? DisabledOn { get; set; }
    }
}
