// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.CallbackRegister")]
    public class CallbackRegister
    {
        [Key]
        public int Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public string CreditorId { get; set; }
        public DateTime CallbackDate { get; set; }
        public DateTime CreatedOn { get; set; }
        public int CallbackTime { get; set; }
        public string? PolicyId { get; set; }
        public string? CampaignId { get; set; }
        public string? ScheduleId { get; set; }
    }
}
