// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.DropCowboyMessageEvents")]
    public class DropCowboyMessageEvents
    {
        [Key]
        public int DropCowboyMessageEventId { get; set; }
        public string UniqueMessageId { get; set; }
        public string? MobileTo { get; set; }
        public string? DropId { get; set; }
        public string? CallerId { get; set; }
        public DateTime AttemptDate { get; set; }
        public string? Status { get; set; }
        public int StatusCode { get; set; }
        public string? Reason { get; set; }
        public bool Dnc { get; set; }
        public bool Spam { get; set; }
        public int Quantity { get; set; }
        public string? ProductCode { get; set; }
        public double ProductCost { get; set; }
        public int ComplianceFee { get; set; }
        public double TtsFee { get; set; }
        public string? NetworkMno { get; set; }
        public string? NetworkNetworkId { get; set; }
        public string? NetworkName { get; set; }
        public string? NetworkType { get; set; }
        public DateTime OccurredAtUtc { get; set; }
        public int CreditorId { get; set; }
        public int CampaignTrackerId { get; set; }
        public int AccountInvoiceId { get; set; }
    }
}
