// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.DropCowboyOutboundMessages")]
    public class DropCowboyOutboundMessages
    {
        [Key]
        public int DropCowboyOutboundMessageId { get; set; }
        public int CreditorId { get; set; }
        public int? CampaignTrackerId { get; set; }
        public int? AccountInvoiceId { get; set; }
        public int? RemitterTemplateId { get; set; }
        public string? CommunicationType { get; set; }
        public string UniqueMessageId { get; set; }
        public string? MobileTo { get; set; }
        public string? MessageBody { get; set; }
        public string? MediaUrl { get; set; }
        public int? Attempt { get; set; }
        public int? ValidityPeriod { get; set; }
        public string? StatusCallback { get; set; }
        public DateTime? OccurredAtUtc { get; set; }
        public bool IsTest { get; set; }
    }
}
