// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.EmailMessage")]
    public class EmailMessage
    {
        public long EmailMessageId { get; set; }
        public int GatewayId { get; set; }
        public string FromEmailAddress { get; set; }
        public string Subject { get; set; }
        public string? Body { get; set; }
        public DateTime? SendAfterUTC { get; set; }
        public DateTime? SendWindowStartUTC { get; set; }
        public DateTime? SendWindowEndUTC { get; set; }
        public DateTime? SentOnUTC { get; set; }
        public string? GatewaySendReceipt { get; set; }
    }
}
