// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.EmailMessageRecipient")]
    public class EmailMessageRecipient
    {
        public long EmailMessageRecipientId { get; set; }
        public long EmailMessageId { get; set; }
        public int EmailMessageRecipientTypeId { get; set; }
        public string EmailAddress { get; set; }
    }
}
