// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.InboundShortCodeReply")]
    public class InboundShortCodeReply
    {
        [Key]
        public int Id { get; set; }
        public int CreditorId { get; set; }
        public int Source { get; set; }
        public string? To { get; set; }
        public string? From { get; set; }
        public string? Body { get; set; }
        public string? MessagingServiceSid { get; set; }
        public string? ShortCodeReply { get; set; }
        public DateTime? ReceivedOn { get; set; }
        public DateTime? ReplyOn { get; set; }
    }
}
