// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.InboundMessageReadEvent")]
    public class InboundMessageReadEvent
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string InboundMessageRecordId { get; set; }
        public string UserId { get; set; }
        public DateTime Occurred { get; set; }
        public DateTime? Persisted { get; set; }
    }
}
