// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.InboundIntent")]
    public class InboundIntent
    {
        [Key]
        public int Id { get; set; }
        public string InboundIntentId { get; set; }
        public string CreditorId { get; set; }
        public string IntentId { get; set; }
        public string DisplayName { get; set; }
        public string? Description { get; set; }
        public decimal Weighting { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? DeletedOn { get; set; }
        public string? DeletedBy { get; set; }
    }
}
