// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.MessageSentToday")]
    public class MessageSentToday
    {
        [Key]
        public long MessageSentTodayId { get; set; }
        public int CreditorId { get; set; }
        public int AccountInvoiceId { get; set; }
        public int TemplateId { get; set; }
        public int NotificationTypeId { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
