// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.NotificationLogs")]
    public class NotificationLogs
    {
        [Key]
        public string Id { get; set; }
        public string IntegrationLinkId { get; set; }
        public string CreditorId { get; set; }
        public string TemplateId { get; set; }
        public int NotificationTypeId { get; set; }
        public string SentToAddress { get; set; }
        public DateTime? SentAt { get; set; }
        public string? MachineName { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string? CampaignId { get; set; }
    }
}
