// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.NotificationSendBlocked")]
    public class NotificationSendBlocked
    {
        [Key]
        public Guid Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public int NotificationType { get; set; }
        public int CommunicationTemplate { get; set; }
        public int Reason { get; set; }
        public DateTime When { get; set; }
    }
}
