// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.ProcessedMessages")]
    public class ProcessedMessages
    {
        [Key]
        public string Id { get; set; }
        public string UniqueMessageId { get; set; }
        public string IntegrationLinkId { get; set; }
        public string CreditorId { get; set; }
        public string ProcessedBy { get; set; }
        public DateTime ProcessedAt { get; set; }
    }
}
