// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.SendGridOutboundMessages")]
    public class SendGridOutboundMessages
    {
        [Key]
        public int SendGridOutboundMessageId { get; set; }
        public int CreditorId { get; set; }
        public int? CampaignTrackerId { get; set; }
        public int? AccountInvoiceId { get; set; }
        public int? RemitterTemplateId { get; set; }
        public string? CommunicationType { get; set; }
        public string UniqueMessageId { get; set; }
        public string? EmailTo { get; set; }
        public string? EmailFrom { get; set; }
        public string? EmailCC { get; set; }
        public string? EmailBCC { get; set; }
        public string? ReplyTo { get; set; }
        public string? Subject { get; set; }
        public string? Content { get; set; }
        public string? DynamicTemplateData { get; set; }
        public string? Attachments { get; set; }
        public string? SendGridTemplateId { get; set; }
        public string? Categories { get; set; }
        public string? CustomArgs { get; set; }
        public string? BatchId { get; set; }
        public string? IpPoolName { get; set; }
        public DateTime? OccurredAtUtc { get; set; }
        public bool IsTest { get; set; }
        public DateTime? ArchivedOnUtc { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        [Computed]
        public DateTime? ComputedCreatedOnDoyUtc { get; set; }
    }
}
