// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.SendGridMessageEvents")]
    public class SendGridMessageEvents
    {
        [Key]
        public int SendGridMessageEventId { get; set; }
        public int CreditorId { get; set; }
        public int? AccountInvoiceId { get; set; }
        public string UniqueMessageId { get; set; }
        public string? Email { get; set; }
        public DateTime? OccurredAt { get; set; }
        public string? SmtpId { get; set; }
        public string? Event { get; set; }
        public string? Reason { get; set; }
        public string? Status { get; set; }
        public string? IpAddress { get; set; }
        public string? CertificateError { get; set; }
        public int? Attempt { get; set; }
        public string? CommunicationTemplate { get; set; }
        public string? Category { get; set; }
        public string? Response { get; set; }
        public string? BccAddress { get; set; }
        public string? Source { get; set; }
        public string? SendGridEventId { get; set; }
        public string? SendGridMessageId { get; set; }
        public string? UserAgent { get; set; }
        public string? UniqueArgs { get; set; }
        public string? BounceClassification { get; set; }
        public string? SendGridType { get; set; }
        public bool IsBlacklisted { get; set; }
        public string? AccountInvoiceLegacyId { get; set; }
        public string? CampaignId { get; set; }
        public DateTime? ForwardedOnUtc { get; set; }
    }
}
