// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.SkitAIMessageEvent")]
    public class SkitAIMessageEventt // todo: fix or deal with tables with columns matching the table name
    {
        [Key]
        public int SkitAIMessageEvent { get; set; }
        public int CreditorId { get; set; }
        public int AccountInvoiceId { get; set; }
        public string? PaymentKey { get; set; }
        public DateTime? CallTime { get; set; }
        public string? CallerNumber { get; set; }
        public string? AccountNumber { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public decimal? CallDuration { get; set; }
        public string? CallType { get; set; }
        public string? ContactType { get; set; }
        public decimal? DueAmount { get; set; }
        public DateTime? PaymentDueDate { get; set; }
        public decimal? PaymentAmount { get; set; }
        public string? TransactionReferenceCode { get; set; }
        public Guid CallUUID { get; set; }
        public string? CallHistory { get; set; }
        public string? Disposition { get; set; }
        public string? CallReportLink { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
