// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.SMSCommandRequest")]
    public class SMSCommandRequest
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string InboundMessageRecordId { get; set; }
        public string Command { get; set; }
        public DateTime Occurred { get; set; }
    }
}
