// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.State")]
    public class State
    {
        public long Id { get; set; }
        public long JobId { get; set; }
        public string Name { get; set; }
        public string? Reason { get; set; }
        public DateTime CreatedAt { get; set; }
        public string? Data { get; set; }
        // NOTE: Composite primary key detected; use EF Core Fluent API to configure:
        // modelBuilder.Entity<State>().HasKey(e => new { /* add key parts here */ });
    }
}
