// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.TelgorithmMessageEventGroupRecipient")]
    public class TelgorithmMessageEventGroupRecipient
    {
        [Key]
        public long TelgorithmMessageEventGroupRecipientId { get; set; }
        public long TelgorithmOutboundMessageId { get; set; }
        public string To { get; set; }
        public string? Carrier { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
