// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.TelgorithmInboundMessage")]
    public class TelgorithmInboundMessage
    {
        [Key]
        public long TelgorithmInboundMessageId { get; set; }
        public int CreditorId { get; set; }
        public int? AccountInvoiceId { get; set; }
        public string WebhookSid { get; set; }
        public string Sid { get; set; }
        public string? From { get; set; }
        public string To { get; set; }
        public string AdditionalRecipients { get; set; }
        public DateTime EventDateUtc { get; set; }
        public string? Text { get; set; }
        public string? MediaUrls { get; set; }
        public int SegmentCount { get; set; }
        public string? ConversationMetadata { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ArchivedOnUtc { get; set; }
        public DateTime? ForwardedOnUtc { get; set; }
    }
}
