// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.TelgorithmMessageEvent")]
    public class TelgorithmMessageEvent
    {
        [Key]
        public long TelgorithmMessageEventId { get; set; }
        public int CreditorId { get; set; }
        public int? AccountInvoiceId { get; set; }
        public string WebhookSid { get; set; }
        public string Sid { get; set; }
        public string From { get; set; }
        public string? To { get; set; }
        public DateTime EventDateUtc { get; set; }
        public string StatusResponseCode { get; set; }
        public int ErrorCodeResponseCode { get; set; }
        public string? ErrorDescription { get; set; }
        public int SegmentCount { get; set; }
        public string? Carrier { get; set; }
        public string? ConversationMetadata { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ForwardedOnUtc { get; set; }
    }
}
