// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.TwilioTextToPaySignal")]
    public class TwilioTextToPaySignal
    {
        [Key]
        public long TwilioTextToPaySignalId { get; set; }
        public int TwilioInboundMessageId { get; set; }
        public int TextToPayKeywordId { get; set; }
        public int CreditorId { get; set; }
        public string FromNumber { get; set; }
        public string ToNumber { get; set; }
        public DateTime? ProcessedOnUtc { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
