// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.TwilioInboundMessages")]
    public class TwilioInboundMessages
    {
        [Key]
        public int TwilioInboundMessageId { get; set; }
        public int CreditorId { get; set; }
        public string? AccountSid { get; set; }
        public string? FromCity { get; set; }
        public string? FromCountry { get; set; }
        public string? FromState { get; set; }
        public string? FromZip { get; set; }
        public string? MessageBody { get; set; }
        public string? MessageSid { get; set; }
        public string? MessagingServiceSid { get; set; }
        public string? MobileFrom { get; set; }
        public string? MobileTo { get; set; }
        public int NumMedia { get; set; }
        public int NumSegments { get; set; }
        public string? SmsMessageSid { get; set; }
        public string? ToCity { get; set; }
        public string? ToCountry { get; set; }
        public string? ToState { get; set; }
        public string? ToZip { get; set; }
        public DateTime? OccurredAtUtc { get; set; }
        public bool IsBlacklisted { get; set; }
        public DateTime? ArchivedOnUtc { get; set; }
        public DateTime? ForwardedOnUtc { get; set; }
    }
}
