// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.TwilioMessageEvents")]
    public class TwilioMessageEvents
    {
        [Key]
        public int TwilioMessageEventId { get; set; }
        public string UniqueMessageId { get; set; }
        public string? MobileTo { get; set; }
        public string? MobileFrom { get; set; }
        public string? AccountSid { get; set; }
        public string? MessagingServiceSid { get; set; }
        public string? MessageStatus { get; set; }
        public string? MessageSid { get; set; }
        public string? ApiVersion { get; set; }
        public string? ErrorCode { get; set; }
        public string? ErrorMessage { get; set; }
        public DateTime OccurredAtUtc { get; set; }
        public int CreditorId { get; set; }
        public int CampaignTrackerId { get; set; }
        public int AccountInvoiceId { get; set; }
        public DateTime? ForwardedOnUtc { get; set; }
    }
}
