// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.TwilioOutboundMessages")]
    public class TwilioOutboundMessages
    {
        [Key]
        public int TwilioOutboundMessageId { get; set; }
        public int CreditorId { get; set; }
        public int? CampaignTrackerId { get; set; }
        public int? AccountInvoiceId { get; set; }
        public int? RemitterTemplateId { get; set; }
        public string? CommunicationType { get; set; }
        public string UniqueMessageId { get; set; }
        public string? MobileFrom { get; set; }
        public string? MobileTo { get; set; }
        public string? MessageBody { get; set; }
        public string? AccountSid { get; set; }
        public string? MessagingServiceSid { get; set; }
        public string? MediaUrl { get; set; }
        public string? ContentSid { get; set; }
        public string? ApplicationSid { get; set; }
        public int? Attempt { get; set; }
        public int? ValidityPeriod { get; set; }
        public string? ContentVariables { get; set; }
        public string? StatusCallback { get; set; }
        public bool ProvideFeedback { get; set; }
        public bool ShortenUrls { get; set; }
        public bool SendAsMms { get; set; }
        public DateTime? OccurredAtUtc { get; set; }
        public bool IsTest { get; set; }
        public DateTime? ArchivedOnUtc { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        [Computed]
        public DateTime? ComputedCreatedOnDoyUtc { get; set; }
    }
}
