// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Comms
{
    [Table("Comms.TwilioInboundMessage")]
    public class TwilioInboundMessage
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string? ApiVersion { get; set; }
        public int NumSegments { get; set; }
        public string? FromCountry { get; set; }
        public string? ToZip { get; set; }
        public string? FromCity { get; set; }
        public string? ToCity { get; set; }
        public string? SmsStatus { get; set; }
        public string? To { get; set; }
        public string? ToCountry { get; set; }
        public string? AccountSid { get; set; }
        public string? FromState { get; set; }
        public string? MessageSid { get; set; }
        public string? FromZip { get; set; }
        public string? SmsMessageSid { get; set; }
        public string? SmsSid { get; set; }
        public string? Body { get; set; }
        public string? From { get; set; }
        public string? ToState { get; set; }
        public int NumMedia { get; set; }
        public string? MessagingServiceSid { get; set; }
        public DateTime ReceivedOn { get; set; }
        public string? IntentKey { get; set; }
        public string? IntentDisplayName { get; set; }
        public double? IntentDetectionConfidence { get; set; }
        public double? SentimentScore { get; set; }
        public double? SentimentMagnitude { get; set; }
        public string? IntentId { get; set; }
    }
}
