// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Comms
{
    [Table("Comms.VoiceMailCallback")]
    public class VoiceMailCallback
    {
        public long Id { get; set; }
        public string? CreditorId { get; set; }
        public string? InvoiceId { get; set; }
        public string ForeignId { get; set; }
        public string Status { get; set; }
        public string? RequestBody { get; set; }
        public string? ResponseBody { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
    }
}
