// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.ReferenceData
{
    [Table("ReferenceData.Calendar")]
    public class Calendar
    {
        [Key]
        public DateTime Date { get; set; }
        [Computed]
        public int? Day { get; set; }
        [Computed]
        public int? Month { get; set; }
        [Computed]
        public DateTime? FirstOfMonth { get; set; }
        [Computed]
        public string? MonthName { get; set; }
        [Computed]
        public int? Week { get; set; }
        [Computed]
        public int? ISOweek { get; set; }
        [Computed]
        public int? DayOfWeek { get; set; }
        [Computed]
        public int? Quarter { get; set; }
        [Computed]
        public int? Year { get; set; }
        [Computed]
        public DateTime? FirstOfYear { get; set; }
        [Computed]
        public string? Style112 { get; set; }
        [Computed]
        public string? Style103 { get; set; }
    }
}
