// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.ReferenceData
{
    [Table("ReferenceData.ResponseCode")]
    public class ResponseCode
    {
        public string TypeName { get; set; }
        public string Code { get; set; }
        public string? Description { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
