// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Policy
{
    [Table("Policy.AccountPolicyManagement")]
    public class AccountPolicyManagement
    {
        [Key]
        public int Id { get; set; }
        public string AccountPolicyManagementId { get; set; }
        public string CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string? NextPolicyId { get; set; }
        public DateTime? NextMessageTriggerDate { get; set; }
        public bool IsSuspended { get; set; }
        public DateTime? SuspendedUntil { get; set; }
    }
}
