// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Policy
{
    [Table("Policy.InvoicePolicyTracking")]
    public class InvoicePolicyTracking
    {
        [Key]
        public int Id { get; set; }
        public string InvoicePolicyTrackingId { get; set; }
        public string AccountInvoiceId { get; set; }
        public DateTime InvoiceDueDate { get; set; }
        public bool SuspendAllPolicies { get; set; }
        public DateTime? SuspendUntil { get; set; }
        public DateTime? SendNextPolicyAt { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }
}
