// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Policy
{
    [Table("Policy.Policy")]
    public class Policy
    {
        [Key]
        public int Id { get; set; }
        public string PolicyId { get; set; }
        public string AccountPolicyManagementId { get; set; }
        public string CreditorId { get; set; }
        public string Name { get; set; }
        public int TriggerDaysAfterDue { get; set; }
        public int PolicyStatus { get; set; }
        public DateTime? TriggeredOnDate { get; set; }
        public DateTime? SentOnDate { get; set; }
        public DateTime? PaidOnDate { get; set; }
    }
}
