// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Policy
{
    [Table("Policy.PolicyTrackingLog")]
    public class PolicyTrackingLog
    {
        [Key]
        public int Id { get; set; }
        public string InvoicePolicyTrackingId { get; set; }
        public string PolicyRangeId { get; set; }
        public DateTime TriggeredOn { get; set; }
    }
}
