// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ETL
{
    public enum DataSourceFieldMappingType
    {
        Unknown = 0,
        Column = 1,
        ConstantValue = 2,
        Enumeration = 3,
    }
}
