// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
namespace Remitter.Models.Sql.Main.Enums.ETL
{
    public enum DataSourceFieldMappingType
    {
        Unknown = 0,
        Column = 1,
        ConstantValue = 2,
        Enumeration = 3,
    }
}
