// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ETL
{
    public enum FileMappingType
    {
        Unknown = 0,
        Payment = 1,
        Invoice = 2,
        Contact = 3,
        MetaData = 4,
        InvoiceConfig = 5,
    }
}
