// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Enums.ETL
{
    public enum StringFormatType
    {
        Unknown = 0,
        String = 1,
        Decimal = 2,
        Number = 3,
        Boolean = 4,
        DateTime = 5,
    }
}
