// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables
{
    [Table("dbo.AzureSQLMaintenanceLog")]
    public class AzureSQLMaintenanceLog
    {
        [Key]
        public long Id { get; set; }
        public DateTime? OperationTime { get; set; }
        public string? Command { get; set; }
        public string? ExtraInfo { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public string? StatusMessage { get; set; }
    }
}
