// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.CallbackConfigWeekendRange")]
    public class CallbackConfigWeekendRange
    {
        [Key]
        public int CallbackConfigWeekendRangeId { get; set; }
        public string CreditorId { get; set; }
        public string? Label { get; set; }
        public string? From { get; set; }
        public string? To { get; set; }
        public string? Key { get; set; }
    }
}
