// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.CallbackConfig")]
    public class CallbackConfig
    {
        [Key]
        public int CallbackConfigId { get; set; }
        public string CreditorId { get; set; }
        public int? PlusDayStart { get; set; }
        public int? PlusDayLimit { get; set; }
        public bool? AllowSaturday { get; set; }
        public bool? AllowSunday { get; set; }
        public string? DisplayOnlyFormat { get; set; }
        public bool IsCallNowButtonEnabled { get; set; }
        public bool IsRequestCallbackButtonEnabled { get; set; }
    }
}
