// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.CallbackCustomer")]
    public class CallbackCustomer
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string InvoiceId { get; set; }
        public DateTime CallbackDate { get; set; }
        public string? CallbackTime { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
