// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.ComplianceSettings")]
    public class ComplianceSettings
    {
        [Key]
        public int ComplianceSettingId { get; set; }
        public int CreditorId { get; set; }
        public int? EnableCompliance { get; set; }
        public TimeSpan? WindowStartTime { get; set; }
        public TimeSpan? WindowEndTime { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
