// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.ConfigOverride")]
    public class ConfigOverride
    {
        [Key]
        public int CreditorConfigOverrideId { get; set; }
        public int CreditorId { get; set; }
        public string? Entity { get; set; }
        public string? EntityId { get; set; }
        public string? ArchiveId { get; set; }
        public string? Disclosure { get; set; }
        public int IsEnabledSMS { get; set; }
        public int IsEnabledPaymentPlans { get; set; }
        public string? CreditCardGateway { get; set; }
        public string? BankAccountGateway { get; set; }
        public string? DebitCardGateway { get; set; }
        public string? PayPalGateway { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
