// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.CreditorPaymentRedirectToExternalUrl")]
    public class CreditorPaymentRedirectToExternalUrl
    {
        [Key]
        public int CreditorPaymentRedirectToExternalUrlId { get; set; }
        public string CreditorId { get; set; }
        public bool? IsAllowRedirectToExternalUrl { get; set; }
        public string? AccountStatusList { get; set; }
        public string? ExternalUrl { get; set; }
        public int? WaitingTime { get; set; }
    }
}
