// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.Creditor")]
    public class Creditor
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string TimeZone { get; set; }
        public string CompanyName { get; set; }
        public string? Abn { get; set; }
        public int DaysAfterDueTillDefault { get; set; }
        public bool IsDemoCreditor { get; set; }
        public string? Website { get; set; }
        public string DefaultCurrencyCode { get; set; }
        public string CountryPhoneNumberPrefix { get; set; }
        public string DateFormat { get; set; }
        public string PaymentPortalUrl { get; set; }
        public string? CreatedByUserId { get; set; }
        public string? LastUpdatedByUserId { get; set; }
        public string? CallbackEmailAddress { get; set; }
        public string? CallbackPhoneNumber { get; set; }
        public string CreditorPortalUrl { get; set; }
        public string? EmailFolderName { get; set; }
        public bool BaselineDebtAgeToUploadDate { get; set; }
        public string? SubCreditorName { get; set; }
        public bool BypassPolicySystem { get; set; }
        public int? IndustryVertical { get; set; }
        public int? DebtType { get; set; }
        public string? AccountName { get; set; }
        public int? AccountIndustry { get; set; }
        public int? RepaymentWindowInDays { get; set; }
        public bool SendUpdatePaymentMessage { get; set; }
        public string? BlobStorageName { get; set; }
        public bool SendPaymentPlanEmailReminder { get; set; }
        public bool SendPaymentPlanSmsReminder { get; set; }
        public string? Description { get; set; }
        public bool EnableSinglePayment { get; set; }
        public bool EnablePaymentPlans { get; set; }
        public bool EnableInvoiceChallenge { get; set; }
        public bool EnableFailedPaymentEmailAlertToCreditor { get; set; }
        public string? AlertsEmailAddress { get; set; }
        public bool EnablePartialPayments { get; set; }
        public double MinimumAllowableInvoiceAmountForPartial { get; set; }
        public double MinimumAllowablePartialAmount { get; set; }
        public bool DisabledEmailNotification { get; set; }
        public bool SendPaymentPlanTenDaysEmailReminder { get; set; }
        public bool? UseCommsBatching { get; set; }
        public string? CommsStrategyTagFieldName { get; set; }
        public bool? IsActive { get; set; }
        public int StateDisclosureUsage { get; set; }
        public string? StateDisclosureDataField { get; set; }
        public string? PaypalGateWay { get; set; }
        public string? BankAccountGateWay { get; set; }
        public string? DebitCardGateWay { get; set; }
        public string? CreditCardGateway { get; set; }
        public bool? EnablePlanExpiryCheck { get; set; }
        public bool? EnableAttachments { get; set; }
        public bool? EnableSchedulePayment { get; set; }
        public bool? EnableUpdateContactInfo { get; set; }
        public string? CallbackRedirectUrl { get; set; }
        public string? CallbackRedirectUrlTitle { get; set; }
        public bool? IsSendByRemitterCampaignsApi { get; set; }
        public int? PaymentPlansPlusDayLimit { get; set; }
        public int IsSettlementPaymentEnabled { get; set; }
        public int? UITemplateSettingId { get; set; }
        public bool? IsVMDropEnabled { get; set; }
        public int? PaymentPlansPlusDayStart { get; set; }
        public int? PaymentPlansPlusDayDefault { get; set; }
        public bool? ToggleCompletePaymentPlanOnInitialEndDate { get; set; }
        public double? MinimumAllowableInvoiceAmountForPaymentPlan { get; set; }
        public int? ClientId { get; set; }
        public bool EndPaymentPlanOnFailedRecurringsSettingsEnable { get; set; }
        public int EndPaymentPlanOnFailedRecurringsSettingsThreshold { get; set; }
        public bool IsTextToPayEnabled { get; set; }
        public int? PaymentGatewayId { get; set; }
        public bool? IsDownPaymentEnabled { get; set; }
        public bool? AdditionalPaymentsWhileOnPaymentPlanEnabled { get; set; }
        public int? SettlementTypeId { get; set; }
    }
}
