// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.CreditorVisualTheme")]
    public class CreditorVisualTheme
    {
        [Key]
        public int Id { get; set; }
        public string? CreditorId { get; set; }
        public int? Product { get; set; }
        public string? PalettePrimary1Color { get; set; }
        public string? PalettePrimary2Color { get; set; }
        public string? PalettePrimary3Color { get; set; }
        public string? PaletteAccent1Color { get; set; }
        public string? PaletteAccent2Color { get; set; }
        public string? PaletteAccent3Color { get; set; }
        public string? PaletteTextColor { get; set; }
        public string? PaletteSecondaryTextColor { get; set; }
        public string? PaletteAlternateTextColor { get; set; }
        public string? PaletteCanvasColor { get; set; }
        public string? PaletteAlternateCanvasColor { get; set; }
        public string? PaletteAlternate1Color { get; set; }
        public string? PaletteAlternate2Color { get; set; }
        public string? PaletteBorderColor { get; set; }
        public string? PaletteDisabledColor { get; set; }
        public string? PalettePickerHeaderColor { get; set; }
        public string? PaletteShadowColor { get; set; }
    }
}
