// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.CreditorSecurityConfig")]
    public class CreditorSecurityConfig
    {
        public string? Id { get; set; }
        public string? CreditorId { get; set; }
        public string? ClientId { get; set; }
        public string? ClientSecret { get; set; }
        public string? PrimaryToken { get; set; }
        public string? SecondaryToken { get; set; }
    }
}
