// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.FailedPaymentRetryRule")]
    public class FailedPaymentRetryRule
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public bool Enabled { get; set; }
        public int? MaximumRetry { get; set; }
        public double? RetryIntervalInHours { get; set; }
        public bool EndPaymentPlan { get; set; }
        public bool? IsLastPaymentStatusDeclinedAllowRetry { get; set; }
    }
}
