// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.LocalizationConfigs")]
    public class LocalizationConfigs
    {
        [Key]
        public int LocalizationConfigId { get; set; }
        public int CreditorId { get; set; }
        public string Language { get; set; }
        public string Key { get; set; }
        public string? Override { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
