// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.NotificationSchedule")]
    public class NotificationSchedule
    {
        [Key]
        public int Id { get; set; }
        public string NotificationScheduleId { get; set; }
        public string CreditorId { get; set; }
        public string NotificationTimeZone { get; set; }
        public string? DateRestrictions { get; set; }
    }
}
