// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.NotificationSettings")]
    public class NotificationSettings
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public int SmsPlatform { get; set; }
        public int EmailPlatform { get; set; }
        public int? VMPlatform { get; set; }
        public int? AIVoiceAgentPlatform { get; set; }
    }
}
