// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.NotificationDateRestrictions")]
    public class NotificationDateRestrictions
    {
        [Key]
        public int NotificationDateRestrictionId { get; set; }
        public int CreditorId { get; set; }
        public string? NotificationTimeZone { get; set; }
        public DateTime? RestrictedDate { get; set; }
        public string? Note { get; set; }
        public int IsActive { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
