// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.PaymentPlanSetting")]
    public class PaymentPlanSetting
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public int Frequency { get; set; }
        public double InterestRate { get; set; }
        public double ApplicationFee { get; set; }
        public double ExitFee { get; set; }
        public double PlanFee { get; set; }
        public bool? IsEnabled { get; set; }
        public double MinAmount { get; set; }
        public double LoanTerm { get; set; }
        public double? OrderNo { get; set; }
        public int? Ordernod { get; set; }
    }
}
