// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.PolicyRangePresets")]
    public class PolicyRangePresets
    {
        [Key]
        public int PolicyRangePresetId { get; set; }
        public int CreditorId { get; set; }
        public string PolicyId { get; set; }
        public int AgeRangeStart { get; set; }
        public int Interval { get; set; }
        public int IsEnabled { get; set; }
        public string? IsArchived { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
