// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.PolicyNotifications")]
    public class PolicyNotifications
    {
        [Key]
        public int PolicyNotificationsId { get; set; }
        public int CreditorId { get; set; }
        public string PolicyId { get; set; }
        public int NotificationType { get; set; }
        public int IsMms { get; set; }
        public string? Subject { get; set; }
        public string Template { get; set; }
        public string? TemplateMedia { get; set; }
        public int IsEnabled { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
