// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.ScheduleDay")]
    public class ScheduleDay
    {
        [Key]
        public int Id { get; set; }
        public int NotificationScheduleId { get; set; }
        public string Name { get; set; }
        public TimeSpan? PreferredTime { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public bool IsActive { get; set; }
    }
}
