// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.SendGridConfigs")]
    public class SendGridConfigs
    {
        [Key]
        public int CreditorId { get; set; }
        public string AccountId { get; set; }
        public string Username { get; set; }
        public string ApiKeyId { get; set; }
        public string ApiKey { get; set; }
        public string SenderAddress { get; set; }
        public string? SenderFullName { get; set; }
        public string? BccAddress { get; set; }
        public string? BlockAddresses { get; set; }
        public bool? IsActive { get; set; }
    }
}
