// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.SettingsTransaction")]
    public class SettingsTransaction
    {
        [Key]
        public int Id { get; set; }
        public string? CreditorId { get; set; }
        public string? UserId { get; set; }
        public string UpdateType { get; set; }
        public string MessageId { get; set; }
        public string MessageBody { get; set; }
        public DateTime TransactionDate { get; set; }
    }
}
