// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.SettlementPaymentSetting")]
    public class SettlementPaymentSetting
    {
        public int Id { get; set; }
        public int CreditorId { get; set; }
        public decimal MinAmount { get; set; }
        public decimal MaxAmount { get; set; }
        public int? TransectionType { get; set; }
        public int Frequency { get; set; }
        public decimal SettlementPercentage { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime UpdatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
        public int? MinDurationDays { get; set; }
        public int? MaxDurationDays { get; set; }
        public int? SettlementTypeId { get; set; }
    }
}
