// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.SharingSetting")]
    public class SharingSetting
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public bool EnableSharing { get; set; }
        public string? Message { get; set; }
    }
}
