// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.TextToPayKeyword")]
    public class TextToPayKeyword
    {
        [Key]
        public int TextToPayKeywordId { get; set; }
        public int TemplateId { get; set; }
        public int? FallbackTemplateId { get; set; }
        public bool IsCardLookUp { get; set; }
        public bool IsMakePayment { get; set; }
        public int? CreditorId { get; set; }
        public string Keyword { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
