// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.UITemplateSetting")]
    public class UITemplateSetting
    {
        public int UITemplateSettingId { get; set; }
        public string? TemplateName { get; set; }
        public string? TemplateScreenShotUrl { get; set; }
        public string? TemplateDescription { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime UpdatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
        public bool IsDefault { get; set; }
    }
}
