// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.VisualThemeConfigPalette")]
    public class VisualThemeConfigPalette
    {
        [Key]
        public int VisualThemeConfigPaletteId { get; set; }
        public string CreditorId { get; set; }
        public string Primary1Color { get; set; }
        public string Primary2Color { get; set; }
        public string Primary3Color { get; set; }
        public string Accent1Color { get; set; }
        public string Accent2Color { get; set; }
        public string Accent3Color { get; set; }
        public string TextColor { get; set; }
        public string SecondaryTextColor { get; set; }
        public string AlternateTextColor { get; set; }
        public string CanvasColor { get; set; }
        public string AlternateCanvasColor { get; set; }
        public string Alternate1Color { get; set; }
        public string Alternate2Color { get; set; }
        public string BorderColor { get; set; }
        public string DisabledColor { get; set; }
        public string PickerHeaderColor { get; set; }
        public string ShadowColor { get; set; }
    }
}
