// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.VisualThemeConfig")]
    public class VisualThemeConfig
    {
        [Key]
        public int VisualThemeConfigId { get; set; }
        public string CreditorId { get; set; }
        public string FontFamily { get; set; }
        public string Product { get; set; }
    }
}
