// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Creditors
{
    [Table("Creditors.VisualThemeConfigSpacing")]
    public class VisualThemeConfigSpacing
    {
        [Key]
        public int VisualThemeConfigSpacingId { get; set; }
        public string CreditorId { get; set; }
        public int IconSize { get; set; }
        public int DesktopGutter { get; set; }
        public int DesktopGutterMore { get; set; }
        public int DesktopGutterLess { get; set; }
        public int DesktopKeylineIncrement { get; set; }
        public int DesktopDropDownMenuItemHeight { get; set; }
        public int DesktopDropDownMenuFontSize { get; set; }
        public int DesktopDrawerMenuItemHeight { get; set; }
        public int DesktopSubheaderHeight { get; set; }
        public int DesktopToolbarHeight { get; set; }
        public int DesktopGutterMini { get; set; }
    }
}
