// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.WebsiteSettings")]
    public class WebsiteSettings
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string? DesktopLogo { get; set; }
        public string? EmailLogo { get; set; }
        public string? MobileLogo { get; set; }
        public string? LegalActionText { get; set; }
        public string? OutstandingText { get; set; }
        public string? TermsAndConditions { get; set; }
        public string? DefaultText { get; set; }
        public string? DefaultDocument { get; set; }
        public string? UpfrontAmountMessage { get; set; }
        public string? ConfirmText { get; set; }
        public string? CreatePaymentPlanText { get; set; }
        public string? PoweredByLogo { get; set; }
        public string? PoweredByText { get; set; }
        public string? PoweredByUrl { get; set; }
        public string? FavIcon { get; set; }
        public string? ContactButtonText { get; set; }
        public string? ContactButtonPhoneNumber { get; set; }
        public bool Show24HourTime { get; set; }
    }
}
