// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Creditors
{
    [Table("Creditors.WhiteLabelSetting")]
    public class WhiteLabelSetting
    {
        [Key]
        public int WhiteLabelSettingId { get; set; }
        public int CreditorId { get; set; }
        public int? UITemplateSettingId { get; set; }
        public string TokenName { get; set; }
        public string ReplacementValue { get; set; }
        public string? Description { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
