// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Audit
{
    [Table("Audit.AccountInvoiceChangeLog")]
    public class AccountInvoiceChangeLog
    {
        [Key]
        public int AccountInvoiceChangeLogId { get; set; }
        public int? CreditorId { get; set; }
        public string? AccountInvoiceId { get; set; }
        public int? Status { get; set; }
        public DateTime? CreatedOn { get; set; }
    }
}
