// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Webhooks
{
    [Table("Webhooks.Hash")]
    public class Hash
    {
        public string Key { get; set; }
        public string Field { get; set; }
        public string? Value { get; set; }
        public DateTime? ExpireAt { get; set; }
        // NOTE: Composite primary key detected; use EF Core Fluent API to configure:
        // modelBuilder.Entity<Hash>().HasKey(e => new { /* add key parts here */ });
    }
}
