// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Webhooks
{
    [Table("Webhooks.Server")]
    public class Server
    {
        [Key]
        public string Id { get; set; }
        public string? Data { get; set; }
        public DateTime LastHeartbeat { get; set; }
    }
}
