// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookCustomHeader")]
    public class WebhookCustomHeader
    {
        [Key]
        public int WebhookCustomHeaderId { get; set; }
        public int WebhookOAuthSettingId { get; set; }
        public string HeaderKey { get; set; }
        public string HeaderValue { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
