// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookAuthHeader")]
    public class WebhookAuthHeader
    {
        [Key]
        public int WebhookAuthHeaderId { get; set; }
        public int CreditorId { get; set; }
        public int WebhookAuthenticationId { get; set; }
        public string HeaderKey { get; set; }
        public string HeaderValue { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
