// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookFailureSetting")]
    public class WebhookFailureSetting
    {
        [Key]
        public int WebhookFailureSettingId { get; set; }
        public int CreditorId { get; set; }
        public int BatchingIntervalMinutes { get; set; }
        public string FailureNotificationAddress { get; set; }
        public int FailureThreshold { get; set; }
        public bool VerboseLogging { get; set; }
        public string WebhookRequestContentType { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
