// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookForwardingSetting")]
    public class WebhookForwardingSetting
    {
        public int WebhookForwardingSettingId { get; set; }
        public int CreditorId { get; set; }
        public string WebhookRequestContentType { get; set; }
        public string WebhookNotificationAddress { get; set; }
        public int BatchingIntervalInSeconds { get; set; }
        public int BatchSize { get; set; }
        public string EventStatusFilter { get; set; }
        public bool IsEnabled { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
