// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookVersion")]
    public class WebhookVersionn // todo: fix or deal with tables with columns matching the table name
    {
        [Key]
        public int WebhookVersionId { get; set; }
        public int CreditorId { get; set; }
        public string WebhookKey { get; set; }
        public string WebhookVersion { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
