// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookAuthCredential")]
    public class WebhookAuthCredential
    {
        [Key]
        public int WebhookAuthCredentialId { get; set; }
        public int? WebhookOAuthSettingId { get; set; }
        public int CreditorId { get; set; }
        public string AuthCredentialType { get; set; }
        public string? IssuerUri { get; set; }
        public string? ClientId { get; set; }
        public string? ClientSecret { get; set; }
        public string? Audience { get; set; }
        public string? GrantType { get; set; }
        public string? Authority { get; set; }
        public string? BasicAuthToken { get; set; }
        public string? SharedAccessSignature { get; set; }
        public string? AuthScope { get; set; }
        public string? AuthHeaderKey { get; set; }
        public string? AuthHeaderValue { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
        public string? BearerToken { get; set; }
    }
}
