// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookBatchRequestLog")]
    public class WebhookBatchRequestLog
    {
        [Key]
        public long WebhookBatchRequestLogId { get; set; }
        public string EventCorrelationId { get; set; }
        public int BatchSize { get; set; }
        public int? RequestDuration { get; set; }
        public string? RequestId { get; set; }
        public DateTime? RequestTime { get; set; }
        public string? StatusCode { get; set; }
        public string? Response { get; set; }
        public string? ResponseBody { get; set; }
        public bool? IsSuccessful { get; set; }
        public bool? IsArchived { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
