// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookEvent")]
    public class WebhookEvent
    {
        [Key]
        public long WebhookEventId { get; set; }
        public string? ExternalId { get; set; }
        public string? AccountInvoiceId { get; set; }
        public int? Attempts { get; set; }
        public int? CreditorId { get; set; }
        public bool? Dismissed { get; set; }
        public string? EventCorrelationId { get; set; }
        public bool? IsSuccessful { get; set; }
        public string? UrlCalled { get; set; }
        public string? WebhookOperation { get; set; }
        public string? Status { get; set; }
        public string MessageType { get; set; }
        public string? StatusCode { get; set; }
        public string? PaymentType { get; set; }
        public bool IsAdhocPayment { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
