// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookJson")]
    public class WebhookJson
    {
        [Key]
        public long WebhookJsonId { get; set; }
        public long WebhookEventId { get; set; }
        public string PayloadType { get; set; }
        public string JsonPayload { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
    }
}
