// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookOAuthSetting")]
    public class WebhookOAuthSetting
    {
        [Key]
        public int WebhookOAuthSettingId { get; set; }
        public int CreditorId { get; set; }
        public string CertificateName { get; set; }
        public string? GlobalIssuerUri { get; set; }
        public string? GlobalClientId { get; set; }
        public string? GlobalClientSecret { get; set; }
        public string? GlobalAudience { get; set; }
        public string? GlobalGrantType { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
