// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookHandlerSetting")]
    public class WebhookHandlerSetting
    {
        [Key]
        public long WebhookHandlerSettingId { get; set; }
        public int CreditorId { get; set; }
        public string OperationType { get; set; }
        public string EventStatus { get; set; }
        public string EndpointUri { get; set; }
        public string PayloadContentType { get; set; }
        public int BatchIntervalInSeconds { get; set; }
        public int BatchSize { get; set; }
        public bool DirectTranfer { get; set; }
        public bool SendMessageContent { get; set; }
        public bool IsEnabled { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
        public int MaxRetryAttempts { get; set; }
    }
}
