// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Webhooks
{
    [Table("Webhooks.WebhookCallbackSetting")]
    public class WebhookCallbackSetting
    {
        [Key]
        public int WebhookCallbackSettingId { get; set; }
        public int CreditorId { get; set; }
        public string CallBackKey { get; set; }
        public string CallbackValue { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
