// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.AutoStartCampaign")]
    public class AutoStartCampaign
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string AutoStartCampaignId { get; set; }
        public string? PipelineId { get; set; }
        public string Name { get; set; }
        public string? TriggerTagId { get; set; }
        public string? Status { get; set; }
        public string? ExcludingTags { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? ArchivedOn { get; set; }
        public DateTime? PublishedOn { get; set; }
    }
}
