// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.AutomationNotificationSchedule")]
    public class AutomationNotificationSchedule
    {
        [Key]
        public int AutomationNotificationScheduleId { get; set; }
        public int CreditorId { get; set; }
        public int AutomationId { get; set; }
        public string Day { get; set; }
        public string? NotificationTypes { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
