// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.AutomationCampaign")]
    public class AutomationCampaign
    {
        [Key]
        public int AutomationCampaignId { get; set; }
        public string AutomationCampaignName { get; set; }
        public int CreditorId { get; set; }
        public int PlaybookId { get; set; }
        public string? AutomationTag { get; set; }
        public int AutomationCampaignStatusId { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
