// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.Campaign")]
    public class Campaign
    {
        [Key]
        public int Id { get; set; }
        public string? PipelineInstanceId { get; set; }
        public string UniqueId { get; set; }
        public string CreditorId { get; set; }
        public string CampaignId { get; set; }
        public string Name { get; set; }
        public bool SendOnlyToNewRecipients { get; set; }
        public string IncludingTagIds { get; set; }
        public string ExcludingTagIds { get; set; }
        public string? TemplateIds { get; set; }
        public DateTime? DeletedOn { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? ArchivedOn { get; set; }
        public string? IsDeleted { get; set; }
        public string? NotificationTypes { get; set; }
    }
}
