// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.CampaignSnapshot")]
    public class CampaignSnapshot
    {
        [Key]
        public long CampaignSnapshotId { get; set; }
        public int CampaignTrackerId { get; set; }
        public int AccountInvoiceId { get; set; }
        public int AccountContactId { get; set; }
        public string? SmsDeliveryResponse { get; set; }
        public string? EmailDeliveryResponse { get; set; }
        public DateTime? SmsDeliveredOnUtc { get; set; }
        public DateTime? EmailDeliveredOnUtc { get; set; }
        public Guid? UniqueEmailGuid { get; set; }
        public Guid? UniqueMobileMessageGuid { get; set; }
        public DateTime? ArchivedOnUtc { get; set; }
        public DateTime UpdatedAtUtc { get; set; }
        public string UpdatedBy { get; set; }
        public Guid? UniqueVMMessageGuid { get; set; }
        public string? VMDeliveryResponse { get; set; }
        public DateTime? VMDeliveredOnUtc { get; set; }
        public Guid? UniqueAIVoiceMessageGuid { get; set; }
    }
}
