// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.CampaignTracker")]
    public class CampaignTracker
    {
        [Key]
        public int CampaignTrackerId { get; set; }
        public int CreditorId { get; set; }
        public int CampaignId { get; set; }
        public int ScheduleId { get; set; }
        public int? PlaybookId { get; set; }
        public int? DaysFromStart { get; set; }
        public int RecipientCount { get; set; }
        public string? Name { get; set; }
        public int? EmailCommsPlatformId { get; set; }
        public int? SmsCommsPlatformId { get; set; }
        public DateTime? SnapshotExpiryOnUtc { get; set; }
        public DateTime? CampaignPreparedUtc { get; set; }
        public DateTime? CampaignStartTimeUtc { get; set; }
        public DateTime? CampaignFinishTimeUtc { get; set; }
        public string? CompletionMessage { get; set; }
        public DateTime? CancelledOnUtc { get; set; }
        public string? CancelledBy { get; set; }
        public string? CancellationReason { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
        public int? AutomationCampaignId { get; set; }
        public int? PlaybookEntryId { get; set; }
        public bool IsApproved { get; set; }
        public int? RejectedMobileMessageCount { get; set; }
        public int? RejectedEmailCount { get; set; }
        public string? CampaignType { get; set; }
        public string? CommunicationChannels { get; set; }
        public int? RejectedVMCount { get; set; }
        public int? VMCommsPlatformId { get; set; }
        public int? AIVoiceAgentPlatformId { get; set; }
        public int NotificationTypeId { get; set; }
        [Computed]
        public int? Batch { get; set; }
    }
}
