// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.CampaignPipeline")]
    public class CampaignPipeline
    {
        [Key]
        public int Id { get; set; }
        public string PipelineId { get; set; }
        public string? PipelineInstanceId { get; set; }
        public string CreditorId { get; set; }
        public string Name { get; set; }
        public DateTime? DeletedOn { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? ArchivedOn { get; set; }
    }
}
