// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.CampaignSchedule")]
    public class CampaignSchedule
    {
        [Key]
        public int Id { get; set; }
        public string CampaignId { get; set; }
        public string ScheduleId { get; set; }
        public int? CommunicationChannel { get; set; }
        public DateTime StartDateTime { get; set; }
        public string ScheduledByUserId { get; set; }
        public string? ScheduleResult { get; set; }
        public int Status { get; set; }
        public int RecurringInterval { get; set; }
        public int RecurringCount { get; set; }
        public DateTime? EndedOn { get; set; }
        public DateTime? ArchivedOn { get; set; }
        public bool? IsActive { get; set; }
    }
}
