// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.CampaignPipelineInstance")]
    public class CampaignPipelineInstance
    {
        [Key]
        public int Id { get; set; }
        public string CampaignPipelineInstanceId { get; set; }
        public int PipelineId { get; set; }
        public string CreditorId { get; set; }
        public string Name { get; set; }
        public DateTime? DeletedOn { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? ArchivedOn { get; set; }
    }
}
