// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.CampaignTemplate")]
    public class CampaignTemplate
    {
        [Key]
        public int Id { get; set; }
        public string CampaignId { get; set; }
        public string TemplateId { get; set; }
    }
}
