// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.CampaignMessageStatus")]
    public class CampaignMessageStatus
    {
        [Key]
        public int CampaignMessageStatusId { get; set; }
        public int CampaignTrackerId { get; set; }
        public int NotificationTypeId { get; set; }
        public int CommsPlatformId { get; set; }
        public string MessageStatus { get; set; }
        public int MessageStatusCount { get; set; }
        public string? MessageStatusDescription { get; set; }
    }
}
