// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.InvoiceCampaign")]
    public class InvoiceCampaign
    {
        [Key]
        public int Id { get; set; }
        public string InvoiceCampaignTrackingId { get; set; }
        public string AutoStartCampaignId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string? Status { get; set; }
        public DateTime? StartDate { get; set; }
        public int? AdjustedDays { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }
}
