// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.InvoiceCampaignSchedule")]
    public class InvoiceCampaignSchedule
    {
        [Key]
        public int Id { get; set; }
        public string InvoiceCampaignTrackingId { get; set; }
        public string? ScheduleId { get; set; }
        public string CampaignScaffoldId { get; set; }
        public DateTime? SentOn { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? ScheduledSendDate { get; set; }
        public string Status { get; set; }
        public int DaysFromStart { get; set; }
    }
}
