// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.PlaybookRejectedInvoiceTracker")]
    public class PlaybookRejectedInvoiceTracker
    {
        [Key]
        public long PlaybookRejectedInvoiceTrackerId { get; set; }
        public int PlaybookInvoiceTrackerId { get; set; }
        public int CreditorId { get; set; }
        public int AccountInvoiceId { get; set; }
        public int AutomationCampaignId { get; set; }
        public string PlaybookId { get; set; }
        public int? DayCount { get; set; }
        public int? RetryCounter { get; set; }
        public DateTime RejectedDateTime { get; set; }
        public string RejectedBy { get; set; }
        public string Reason { get; set; }
    }
}
