// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.PlaybookEntry")]
    public class PlaybookEntry
    {
        [Key]
        public int PlaybookEntryId { get; set; }
        public int PlaybookId { get; set; }
        public int CreditorId { get; set; }
        public string ScaffoldName { get; set; }
        public bool? IsSendOnlyToNewRecipients { get; set; }
        public string IncludingTagIds { get; set; }
        public string ExcludingTagIds { get; set; }
        public string TemplateIds { get; set; }
        public int DaysFromStart { get; set; }
        public DateTime? TimeOfSendUtc { get; set; }
        public bool? IsBypassScheduleRestriction { get; set; }
        public int ScheduleCommunicationPreferenceId { get; set; }
        public int ScheduleTimePreferenceId { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
        public TimeSpan SendTimeUtc { get; set; }
    }
}
