// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.Playbook")]
    public class Playbook
    {
        [Key]
        public int PlaybookId { get; set; }
        public int CreditorId { get; set; }
        public string PlaybookName { get; set; }
        public int MaximumDays { get; set; }
        public bool IsActive { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
        public int PlaybookStrategyId { get; set; }
    }
}
