// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.PlaybookInvoiceTracker")]
    public class PlaybookInvoiceTracker
    {
        [Key]
        public long PlaybookInvoiceTrackerId { get; set; }
        public int CreditorId { get; set; }
        public int AccountInvoiceId { get; set; }
        public int AutomationCampaignId { get; set; }
        public string PlaybookId { get; set; }
        public int? DayCount { get; set; }
        public int? RetryCounter { get; set; }
        public int? LoopCounter { get; set; }
        public bool IsEnabled { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
