// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.PreparedMessages")]
    public class PreparedMessages
    {
        [Key]
        public long PreparedMessageId { get; set; }
        public int CreditorId { get; set; }
        public long CampaignSnapshotId { get; set; }
        public int CampaignTrackerId { get; set; }
        public Guid UniqueEmailGuid { get; set; }
        public Guid UniqueMobileMessageGuid { get; set; }
        public int? AccountInvoiceId { get; set; }
        public int? AccountContactId { get; set; }
        public string? ZipCode { get; set; }
        public string? EmailTo { get; set; }
        public string? EmailSubject { get; set; }
        public string? EmailBody { get; set; }
        public string? MobileTo { get; set; }
        public string? MobileMessage { get; set; }
        public string? Attachment { get; set; }
        public bool IsTest { get; set; }
        public bool IsMms { get; set; }
        public DateTime? EmailSentUTC { get; set; }
        public DateTime? MobileMessageSentUTC { get; set; }
        public DateTime? ArchivedOnUtc { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public Guid? UniqueAIVoiceMessageGuid { get; set; }
        public DateTime? AIVoiceAgentMessageSentUTC { get; set; }
    }
}
