// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.Scaffold")]
    public class Scaffold
    {
        [Key]
        public int Id { get; set; }
        public string ScaffoldId { get; set; }
        public string CreditorId { get; set; }
        public int? PipelineId { get; set; }
        public int? PipelineInstanceId { get; set; }
        public string Name { get; set; }
        public bool FirstCampaignPipeline { get; set; }
        public bool SendOnlyToNewRecipients { get; set; }
    }
}
