// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.ScaffoldSchedule")]
    public class ScaffoldSchedule
    {
        [Key]
        public int Id { get; set; }
        public int ScaffoldId { get; set; }
        public string CreditorId { get; set; }
        public int DaysFromStartDate { get; set; }
        public int CommunicationChannelId { get; set; }
        public bool BypassScheduleRestriction { get; set; }
        public string TimePreference { get; set; }
        public DateTime? TimeOfSend { get; set; }
    }
}
