// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.ScheduleResultBatchFailures")]
    public class ScheduleResultBatchFailures
    {
        public string ScheduleResultBatchId { get; set; }
        public string IntegrationLinkId { get; set; }
        public string Recipient { get; set; }
        // NOTE: Composite primary key detected; use EF Core Fluent API to configure:
        // modelBuilder.Entity<ScheduleResultBatchFailures>().HasKey(e => new { /* add key parts here */ });
    }
}
