// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.ScheduleResultBatches")]
    public class ScheduleResultBatches
    {
        [Key]
        public string Id { get; set; }
        public string ScheduleResultId { get; set; }
        public int BatchSize { get; set; }
        public int Sent { get; set; }
        public int Blocked { get; set; }
        public int? Failed { get; set; }
        public DateTime? SentOn { get; set; }
        public string? ErrorResponse { get; set; }
    }
}
