// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.ScheduleResults")]
    public class ScheduleResults
    {
        [Key]
        public string Id { get; set; }
        public string MessageId { get; set; }
        public string ScheduleId { get; set; }
        public int NotificationType { get; set; }
        public DateTime ProcessStartedOn { get; set; }
        public DateTime? ProcessEndedOn { get; set; }
        public string? ErrorMessage { get; set; }
    }
}
