// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.SendSubstitution")]
    public class SendSubstitution
    {
        [Key]
        public int SendSubstitutionId { get; set; }
        public int CreditorId { get; set; }
        public int CampaignTrackerId { get; set; }
        public long PreparedMessageId { get; set; }
        public int AccountInvoiceId { get; set; }
        public string SubstitutionKey { get; set; }
        public string SubstitutionValue { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
