// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.SendGridTemplates")]
    public class SendGridTemplates
    {
        [Key]
        public string Id { get; set; }
        public int CreditorId { get; set; }
        public string UniqueTemplateId { get; set; }
        public string? VersionId { get; set; }
        public DateTime VersionUpdatedAt { get; set; }
        public DateTime? TemplateUpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }
}
