// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.TagsScaffold")]
    public class TagsScaffold
    {
        [Key]
        public int Id { get; set; }
        public int ScaffoldId { get; set; }
        public int CampaignTagId { get; set; }
        public string Type { get; set; }
    }
}
