// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.TagsExcludedAutostartCampaign")]
    public class TagsExcludedAutostartCampaign
    {
        [Key]
        public int Id { get; set; }
        public int AutostartCampaignId { get; set; }
        public int CampaignTagId { get; set; }
    }
}
