// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.TagsScaffold")]
    public class TagsScaffold
    {
        [Key]
        public int Id { get; set; }
        public int ScaffoldId { get; set; }
        public int CampaignTagId { get; set; }
        public string Type { get; set; }
    }
}
