// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.TemplateActionHistory")]
    public class TemplateActionHistory
    {
        [Key]
        public int Id { get; set; }
        public string UniqueTemplateId { get; set; }
        public string UserId { get; set; }
        public string? ChangeMade { get; set; }
        public DateTime OccurredOn { get; set; }
    }
}
