// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.TemplateActionHistory")]
    public class TemplateActionHistory
    {
        [Key]
        public int Id { get; set; }
        public string UniqueTemplateId { get; set; }
        public string UserId { get; set; }
        public string? ChangeMade { get; set; }
        public DateTime OccurredOn { get; set; }
    }
}
