// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.TemplatesScaffold")]
    public class TemplatesScaffold
    {
        [Key]
        public int Id { get; set; }
        public int ScaffoldId { get; set; }
        public int TemplateId { get; set; }
    }
}
