// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Campaigns
{
    [Table("Campaigns.TemplateSentiment")]
    public class TemplateSentiment
    {
        [Key]
        public int Id { get; set; }
        public string TemplateId { get; set; }
        public string Language { get; set; }
        public float SentimentScore { get; set; }
        public float SentimentMagnitude { get; set; }
        public DateTime AnalyzedOn { get; set; }
        public DateTime? ArchivedOn { get; set; }
    }
}
