// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.TemplatesScaffold")]
    public class TemplatesScaffold
    {
        [Key]
        public int Id { get; set; }
        public int ScaffoldId { get; set; }
        public int TemplateId { get; set; }
    }
}
