// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.TemplateVM")]
    public class TemplateVM
    {
        public int Id { get; set; }
        public int TemplateId { get; set; }
        public string? AudioName { get; set; }
        public string? AudioUrl { get; set; }
        public string? AudioType { get; set; }
        public string? VoicePreference { get; set; }
        public bool IsSSML { get; set; }
        public bool IsAudio { get; set; }
    }
}
