// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.Template")]
    public class Templlate // todo: fix or deal with tables with columns matching the table name
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string CreditorId { get; set; }
        public string UniqueTemplateId { get; set; }
        public bool HideFromDropDowns { get; set; }
        public int NotificationType { get; set; }
        public bool? IsMMS { get; set; }
        public string? Subject { get; set; }
        public string? Template { get; set; }
        public string? TemplateMedia { get; set; }
        public bool Enabled { get; set; }
        public DateTime? DeletedOn { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? ArchivedOn { get; set; }
        public string? TemplateId { get; set; }
        public int? CommunicationTemplateId { get; set; }
        public int TemplateTypeId { get; set; }
        public string? IsDeleted { get; set; }
    }
}
