// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Campaigns
{
    [Table("Campaigns.TemplateSentimentSentence")]
    public class TemplateSentimentSentence
    {
        [Key]
        public int Id { get; set; }
        public string TemplateId { get; set; }
        public float SentimentScore { get; set; }
        public float SentimentMagnitude { get; set; }
        public int TextBeginOffset { get; set; }
        public string TextContent { get; set; }
        public DateTime AnalyzedOn { get; set; }
    }
}
