// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Reporting
{
    [Table("Reporting.NotificationsDatalakeRun")]
    public class NotificationsDatalakeRun
    {
        [Key]
        public int NotificationsDatalakeRunId { get; set; }
        public string ParametersJson { get; set; }
        public DateTime StartDateTimeUtc { get; set; }
        public DateTime? FinishDateTimeUtc { get; set; }
        public bool? IsSuccess { get; set; }
        public string? CompletionMessage { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
