// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Reporting
{
    [Table("Reporting.NotificationMetricsRun")]
    public class NotificationMetricsRun
    {
        [Key]
        public int NotificationMetricsRunId { get; set; }
        public string ParametersJson { get; set; }
        public DateTime? StartedOnUtc { get; set; }
        public DateTime? FinishedOnUtc { get; set; }
        public DateTime? CancelRequestedOnUtc { get; set; }
        public int DaysRequestedCount { get; set; }
        public int DaysProcessedCount { get; set; }
        public int RowsCapturedCount { get; set; }
        public bool? IsSuccess { get; set; }
        public string? CompletionMessage { get; set; }
        public DateTime? ExpiresOnUtc { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
