// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Reporting
{
    [Table("Reporting.NotificationMetricsRow")]
    public class NotificationMetricsRow
    {
        [Key]
        public long NotificationMetricsRowId { get; set; }
        public int NotificationMetricsRunId { get; set; }
        public string? Name { get; set; }
        public string? SentToAddress { get; set; }
        public string? NotificationType { get; set; }
        public DateTime? OccurredAt { get; set; }
        public string? NotificationStatus { get; set; }
        public string? IntegrationLinkId { get; set; }
        public string? InvoiceNumber { get; set; }
        public string? FailureDetail { get; set; }
        public string? FailureReason { get; set; }
        public string? MessageBody { get; set; }
        public string? TemplateName { get; set; }
        public string RecordSource { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? Deletedby { get; set; }
    }
}
