// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Reporting
{
    [Table("Reporting.PaymentsRow")]
    public class PaymentsRow
    {
        [Key]
        public long PaymentsRowId { get; set; }
        public int PaymentsRunId { get; set; }
        public string? TransactionCorrelationId { get; set; }
        public string? InvoiceIntegrationLinkId { get; set; }
        public decimal? Amount { get; set; }
        public decimal? CurrencyRate { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsVoid { get; set; }
        public DateTime? PaidOnUtc { get; set; }
        public DateTime? PaidOnLocal { get; set; }
        public double? LocalUTCOffsetHours { get; set; }
        public string? PaymentStatus { get; set; }
        public string? TransactionType { get; set; }
        public string? PaymentType { get; set; }
        public string? Reference { get; set; }
        public string? Message { get; set; }
        public string? Strategy { get; set; }
        public string? InvoiceStatus { get; set; }
        public bool? IsExternal { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedBy { get; set; }
    }
}
