// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.AccountTransactionMetaData")]
    public class AccountTransactionMetaData
    {
        [Key]
        public int Id { get; set; }
        public string AccountPaymentId { get; set; }
        public string TransactionCorrelationId { get; set; }
        public string MetaDataName { get; set; }
        public string? MetaDataValue { get; set; }
    }
}
