// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Payments
{
    [Table("Payments.AccountTransaction")]
    public class AccountTransaction
    {
        [Key]
        public int Id { get; set; }
        public string AccountPaymentId { get; set; }
        public string CreditorId { get; set; }
        public string? TransactionId { get; set; }
        public string TransactionCorrelationId { get; set; }
        public string? PaymentExternalReferenceNumber { get; set; }
        public string? Token { get; set; }
        public string? Messages { get; set; }
        public string? CurrencyCode { get; set; }
        public decimal Amount { get; set; }
        public int PaymentStatus { get; set; }
        public int PaymentType { get; set; }
        public DateTime? PaidOn { get; set; }
        public bool Void { get; set; }
        public bool Cancelled { get; set; }
        public int PaymentSyncStatus { get; set; }
        public string? Payload { get; set; }
        public bool IsAdhocPayment { get; set; }
        public DateTime ProcessedOn { get; set; }
        public int TransactionType { get; set; }
        public string? ResponseCode { get; set; }
        public string? ResponseStatus { get; set; }
        public string? ResponseText { get; set; }
        public DateTime? InvoiceDueDate { get; set; }
        public DateTime? RemittedDate { get; set; }
        public decimal? SettlementPercentage { get; set; }
        public string? Api { get; set; }
        public string? StrategyTag { get; set; }
    }
}
