// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.AccountPayment")]
    public class AccountPayment
    {
        [Key]
        public int Id { get; set; }
        public string AccountPaymentId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string CreditorId { get; set; }
        public string PaymentKey { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Updated { get; set; }
    }
}
