// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.BinDatas")]
    public class BinDatas
    {
        [Key]
        public int Id { get; set; }
        public string CardBrand { get; set; }
        public string? IssuingOrganization { get; set; }
        public string? CardType { get; set; }
        public string? Country { get; set; }
        public string? IsoCountryCodeA2 { get; set; }
        public string? IsoCountryCodeA3 { get; set; }
        public string? CardSubType { get; set; }
        public int? IsoNumericCountryCode { get; set; }
    }
}
