// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Payments
{
    [Table("Payments.CreditorBillingFee")]
    public class CreditorBillingFee
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public int FeeType { get; set; }
    }
}
