// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.CreditorTierRepaymentAdminFee")]
    public class CreditorTierRepaymentAdminFee
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public int Frequency { get; set; }
        public decimal Fee { get; set; }
    }
}
