// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Payments
{
    [Table("Payments.CreditorBillingConfig")]
    public class CreditorBillingConfig
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
    }
}
