// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.CronSetting")]
    public class CronSetting
    {
        public int Id { get; set; }
        public int RecordLimit { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime UpdatedOnUtc { get; set; }
        public DateTime? EndTIme { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
        public int? Salary { get; set; }
        public int? Salarys { get; set; }
        public decimal SettlementPercentage { get; set; }
        public decimal? SettlementPercentages { get; set; }
    }
}
