// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Payments
{
    [Table("Payments.DirectACH")]
    public class DirectACH
    {
        [Key]
        public int Id { get; set; }
        public string TransactionCorrelationId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string CreditorId { get; set; }
        public string AccountType { get; set; }
        public string? AccountIssuer { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
    }
}
