// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Payments
{
    [Table("Payments.GatewayTransactions")]
    public class GatewayTransactions
    {
        [Key]
        public int Id { get; set; }
        public string TransactionCorrelationId { get; set; }
        public string IntegrationLinkId { get; set; }
        public string CreditorId { get; set; }
        public int PaymentType { get; set; }
        public string? TokenId { get; set; }
        public decimal Amount { get; set; }
        public DateTime? TransactionDate { get; set; }
        public string ProcessedBy { get; set; }
        public DateTime ProcessedAt { get; set; }
    }
}
