// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.GatewayCardWhitelist")]
    public class GatewayCardWhitelist
    {
        [Key]
        public int Id { get; set; }
        public string CreditorId { get; set; }
        public string CardBrand { get; set; }
        public string? CardSubType { get; set; }
        public DateTime Created { get; set; }
        public int PaymentType { get; set; }
    }
}
