// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.PaymentInstrument")]
    public class PaymentInstrument
    {
        [Key]
        public int Id { get; set; }
        public string? AccountContactId { get; set; }
        public string? PaymentInstrumentId { get; set; }
        public string? TokenId { get; set; }
        public string? AccountType { get; set; }
        public string? AccountName { get; set; }
        public string? AccountNumber { get; set; }
        public string? ExpiryMonth { get; set; }
        public string? ExpiryYear { get; set; }
        public string? IssuerNetwork { get; set; }
        public string? IssuerName { get; set; }
        public string? IssuerLogo { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        public int? PaymentType { get; set; }
        public string? BsbNumber { get; set; }
        public DateTime? CreatedOnUtc { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? PostalCode { get; set; }
    }
}
