// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.PaymentRequestResult")]
    public class PaymentRequestResult
    {
        [Key]
        public int PaymentRequestResultId { get; set; }
        public int CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string? TransactionCorrelationId { get; set; }
        public string? PaymentGatewayReferenceId { get; set; }
        public int PaymentStatus { get; set; }
        public decimal Amount { get; set; }
        public DateTime SubmittedOn { get; set; }
        public DateTime? PaidOn { get; set; }
        public DateTime? DeclinedOn { get; set; }
        public int? ResponseCode { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
