// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.PaymentRequestHttpCall")]
    public class PaymentRequestHttpCall
    {
        [Key]
        public int PaymentRequestHttpCallId { get; set; }
        public int PaymentRequestResultId { get; set; }
        public string RawRequest { get; set; }
        public string RawResponse { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
