// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.PaymentRequest")]
    public class PaymentRequest
    {
        [Key]
        public int PaymentRequestId { get; set; }
        public string CreditorId { get; set; }
        public string AccountInvoiceId { get; set; }
        public int PaymentTypeId { get; set; }
        public decimal Amount { get; set; }
        public string PaymentToken { get; set; }
        public string RequestBody { get; set; }
        public bool IsProcessing { get; set; }
        public DateTime SubmittedOn { get; set; }
        public string? SubmittedBy { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
