// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.QFundAccountTransaction")]
    public class QFundAccountTransaction
    {
        [Key]
        public int Id { get; set; }
        public string? CustomerId { get; set; }
        public string? CreditorId { get; set; }
        public string? AccountInvoiceId { get; set; }
        public string? RefferenceId { get; set; }
        public decimal? Amount { get; set; }
        public DateTime? ProcessedOn { get; set; }
        public string? RequestTrackCode { get; set; }
        public string? ResponseCode { get; set; }
        public string? ResponseStatus { get; set; }
        public string? ResponseText { get; set; }
        public int? RetryCount { get; set; }
        public string? TransactionCorrelationId { get; set; }
        public string? TransactionId { get; set; }
        public string? RawRequest { get; set; }
        public string? RawResponse { get; set; }
    }
}
