// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.RecurringPaymentFee")]
    public class RecurringPaymentFee
    {
        [Key]
        public int Id { get; set; }
        public string RecurringPaymentId { get; set; }
        public int FeeType { get; set; }
        public decimal FeeAmount { get; set; }
    }
}
