// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Payments
{
    [Table("Payments.RecurringPaymentDue")]
    public class RecurringPaymentDue
    {
        [Key]
        public int Id { get; set; }
        public string RecurringPaymentDueId { get; set; }
        public string RecurringPaymentId { get; set; }
        public decimal Amount { get; set; }
        public DateTime DueDate { get; set; }
        public bool Active { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Updated { get; set; }
        public decimal Fees { get; set; }
    }
}
