// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Payments
{
    [Table("Payments.RecurringPayment")]
    public class RecurringPayment
    {
        [Key]
        public int Id { get; set; }
        public string RecurringPaymentId { get; set; }
        public string AccountInvoiceId { get; set; }
        public string AccountContactId { get; set; }
        public string CreditorId { get; set; }
        public decimal RecurringAmount { get; set; }
        public int PaymentFrequency { get; set; }
        public int PaymentType { get; set; }
        public string PaymentKey { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool Active { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Updated { get; set; }
        public int ReasonEnded { get; set; }
        public DateTime? UpdatedPaymentPlanDate { get; set; }
        public string? Messages { get; set; }
    }
}
