// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Payments
{
    [Table("Payments.SchedulePlan")]
    public class SchedulePlan
    {
        public int Id { get; set; }
        public string AccountInvoiceId { get; set; }
        public string AccountContactId { get; set; }
        public string CreditorId { get; set; }
        public decimal RecurringAmount { get; set; }
        public string PaymentFrequency { get; set; }
        public int PaymentFlowId { get; set; }
        public int PaymentType { get; set; }
        public string PaymentKey { get; set; }
        public string PaymentToken { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int Active { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public int ReasonEnded { get; set; }
        public string? Messages { get; set; }
        public string? RequestBody { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
        public decimal? SettlementPercentage { get; set; }
        public decimal? SettlementOffer { get; set; }
        public decimal AmountDue { get; set; }
    }
}
