// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.SchedulePlanDue")]
    public class SchedulePlanDue
    {
        public int Id { get; set; }
        public int SchedulePlanId { get; set; }
        public decimal Amount { get; set; }
        public DateTime DueDate { get; set; }
        public bool Active { get; set; }
        public int IsProcessed { get; set; }
        public int Retry { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? TransactionCorrelationId { get; set; }
        public DateTime? ProcessedDate { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
