// automatically generated by Remitter.Tools.Api on 2026-04-27 20:26
using Dapper.Contrib.Extensions;

namespace Remitter.Models.Sql.Main.Tables.Payments
{
    [Table("Payments.SchedulePlanDueLog")]
    public class SchedulePlanDueLog
    {
        public int Id { get; set; }
        public int SchedulePlanDueId { get; set; }
        public int SchedulePlanId { get; set; }
        public string? TransactionCorrelationId { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? Message { get; set; }
        public int? CronId { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
