// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
using Dapper.Contrib.Extensions;

namespace Remitter.Models.SQL.Main.Tables.Payments
{
    [Table("Payments.UserActionDetails")]
    public class UserActionDetails
    {
        [Key]
        public int Id { get; set; }
        public string AccountPaymentId { get; set; }
        public string TransactionCorrelationId { get; set; }
        public string? IpAddress { get; set; }
        public string? UserAgent { get; set; }
    }
}
