// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Views.ETL
{
    public class DataFileMappingView
    {
        public int? DataFileMappingId { get; set; }
        public int? CreditorId { get; set; }
        public int? FileMappingTypeId { get; set; }
        public string? FileMappingType { get; set; }
        public int? DataSourceFieldMappingTypeId { get; set; }
        public string? DataSourceFieldMappingType { get; set; }
        public int? DataSourceFieldId { get; set; }
        public string? SourceFieldName { get; set; }
        public string? ConstantValue { get; set; }
        public int? DataFieldMappingId { get; set; }
        public string? TargetFieldName { get; set; }
        public int? StringFormatTypeId { get; set; }
        public string? StringFormatType { get; set; }
        public int? FieldMappingValueId { get; set; }
        public string? EnumerationMap { get; set; }
    }
}
