// automatically generated by Remitter.Tools.Api on 2026-04-23 05:59
namespace Remitter.Models.SQL.Main.Views.ETL
{
    public class SyncInvoiceProcessView
    {
        public int SyncInvoiceProcessId { get; set; }
        public int? EndpointRequestId { get; set; }
        public int CreditorId { get; set; }
        public DateTime ProcessStartTime { get; set; }
        public DateTime? ProcessFinishTime { get; set; }
        public string? Payload { get; set; }
        public int? ResponseStatusCode { get; set; }
        public string? ResponseBody { get; set; }
        public string? LoggingTraceId { get; set; }
        public int TotalProcessedRecordCount { get; set; }
        public int InvoiceCount { get; set; }
        public int ContactCount { get; set; }
        public int PaymentCount { get; set; }
        public int MetaDataCount { get; set; }
        public int InvoiceConfigCount { get; set; }
        public int VoidedInvoiceCount { get; set; }
        public string? CompletionMessage { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string? UpdatedBy { get; set; }
    }
}
